import test from 'node:test';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_ROOT??'playwright');
const origin=process.env.WONDERWORKS_TEST_URL??'http://127.0.0.1:5173';
if(!['localhost','127.0.0.1'].includes(new URL(origin).hostname))throw Error('Use loopback QA storage.');
async function rest(body,path='/api/workspace'){const response=await fetch(origin+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();assert.equal(response.status,200,JSON.stringify(result));return result;}
async function fixture(run){
 let doc=await rest({action:'project',name:'BL008 browser '+Date.now(),prefix:'GB'});const other=await rest({action:'project',name:'BL008 isolated '+Date.now(),prefix:'GB'});
 const read=async()=>doc=await (await fetch(origin+'/api/workspace?project='+doc.id)).json();
 const remote=async overrides=>{await read();return doc=await rest({project_id:doc.id,expected_workspace_version:doc.version,idempotency_key:crypto.randomUUID(),overrides},'/api/agent-guidance');};
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();page.setDefaultTimeout(7000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const select=async(name)=>{await page.getByRole('combobox',{name:'Current project',exact:true}).click();await page.getByRole('option',{name,exact:true}).click();};
 const reflected=async()=>page.getByText(`Workspace revision ${doc.version} · Durable storage`,{exact:true}).waitFor({state:'attached',timeout:5000});
 const settings=async()=>page.getByRole('tab',{name:'Settings',exact:true}).click();
 const button=name=>page.getByRole('button',{name,exact:true});
 const save=async(name='Save AI guidance')=>{const pending=page.waitForResponse(r=>r.url().endsWith('/api/agent-guidance')&&r.request().method()==='POST');await button(name).click();const response=await pending;assert.equal(response.status(),200,await response.text());await read();await reflected();};
 try{await page.goto(origin);await select(doc.name);await settings();await run({page,context,read,doc:()=>doc,other,remote,select,settings,reflected,button,save});assert.deepEqual(errors,[]);}finally{await browser.close();}
}
test('guidance defaults, edit/save/reload, cancel, reset confirmation and no-op reset',async()=>fixture(async f=>{
 const {page,button}=f;assert.equal(await page.getByLabel('Writing strength (%)',{exact:true}).inputValue(),'60');assert.equal(await page.getByRole('checkbox',{name:/Remind AI/}).isChecked(),true);assert.equal(await page.getByText('Inherited default',{exact:true}).count(),4);
 await button('Edit AI guidance').click();await page.getByLabel('Writing strength (%)',{exact:true}).fill('0');await page.getByRole('checkbox',{name:/Remind AI/}).uncheck();await page.getByLabel('Custom project instructions',{exact:true}).fill('Project instructions 😀 stay intact.');await f.save();assert.equal(f.doc().agentGuidance.revision,1);assert.equal(await page.getByText('Project override',{exact:true}).count(),3);
 await page.reload();await f.select(f.doc().name);await f.settings();assert.equal(await page.getByLabel('Writing strength (%)',{exact:true}).inputValue(),'0');assert.equal(await page.getByLabel('Custom project instructions',{exact:true}).inputValue(),'Project instructions 😀 stay intact.');
 const saved=structuredClone(f.doc());await button('Edit AI guidance').click();await page.getByLabel('Writing strength (%)',{exact:true}).fill('80');await button('Cancel guidance edit').click();assert.deepEqual(await f.read(),saved);
 await button('Restore built-in defaults').click();await button('Keep current guidance').click();assert.deepEqual(await f.read(),saved);await button('Restore built-in defaults').click();await f.save('Confirm restore defaults');assert.equal(await page.getByLabel('Writing strength (%)',{exact:true}).inputValue(),'60');assert.equal(f.doc().agentGuidance.revision,2);const reset=structuredClone(f.doc());await button('Restore built-in defaults').click();await f.save('Confirm restore defaults');assert.deepEqual(f.doc(),reset);
}));
test('remote guidance preserves pending input and original token; explicit reconciliation and project switching are protected',async()=>fixture(async f=>{
 const {page,button}=f;await button('Edit AI guidance').click();await page.getByLabel('Writing strength (%)',{exact:true}).fill('80');await page.getByLabel('Custom project instructions',{exact:true}).fill('My pending text');await page.getByLabel('Custom project instructions',{exact:true}).focus();
 await f.remote({writing_strength_percent:100,custom_instructions:'Saved from another client'});await f.reflected();assert.equal(await page.getByLabel('Writing strength (%)',{exact:true}).inputValue(),'80');assert.equal(await page.getByLabel('Custom project instructions',{exact:true}).inputValue(),'My pending text');assert.equal(await page.getByLabel('Custom project instructions',{exact:true}).evaluate(el=>el===document.activeElement),true);assert.equal(await button('Save AI guidance').isDisabled(),true);
 await button('I reviewed latest; keep my input').click();await f.save();assert.equal(f.doc().agentGuidance.revision,2);assert.equal(f.doc().agentGuidance.overrides.writing_strength_percent,80);
 await button('Edit AI guidance').click();await page.getByLabel('Custom project instructions',{exact:true}).fill('Do not lose this input');await f.select(f.other.name);await page.getByRole('heading',{name:'Keep pending AI guidance?'}).waitFor();await button('Keep editing').click();assert.equal(await page.getByLabel('Custom project instructions',{exact:true}).inputValue(),'Do not lose this input');await f.select(f.other.name);await button('Discard guidance edit').click();await page.getByRole('heading',{name:f.other.name+'.',exact:true}).waitFor();assert.equal(await page.getByLabel('Writing strength (%)',{exact:true}).inputValue(),'60');
}));
test('uncertain settings save retains its original retry arguments after a newer read',async()=>fixture(async f=>{
 const {page,button}=f;await button('Edit AI guidance').click();await page.getByLabel('Custom project instructions',{exact:true}).fill('One durable guidance write');const before=f.doc().version,attempts=[];let first=true;
 await page.route('**/api/agent-guidance',async route=>{attempts.push(route.request().postDataJSON());if(first){first=false;const response=await route.fetch();assert.equal(response.status(),200);await route.abort('failed');}else await route.continue();});
 await button('Save AI guidance').click();await button('Retry original guidance save').waitFor();await f.read();await f.reflected();assert.equal(await page.getByLabel('Custom project instructions',{exact:true}).inputValue(),'One durable guidance write');await button('Retry original guidance save').click();await button('Edit AI guidance').waitFor();assert.deepEqual(attempts[0],attempts[1]);await f.read();assert.equal(f.doc().version,before+1);assert.equal(f.doc().agentGuidance.revision,1);assert.equal(f.doc().history.filter(h=>h.agentGuidance).length,1);
}));
test('keyboard and compact controls explain style preference without claiming compliance',async()=>fixture(async f=>{
 const {page,button}=f;await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});await button('Edit AI guidance').focus();await page.keyboard.press('Enter');await page.getByLabel('Writing strength (%)',{exact:true}).fill('100');await page.locator('.guidance-help summary').focus();await page.keyboard.press('Enter');await page.getByText(/within 5 seconds after the user selects Export/).waitFor();assert.match(await page.locator('.guidance-form').innerText(),/not an ASD score or verified compliance/);assert.equal(await page.getByRole('link',{name:'Official ASD-STE100 guidance'}).getAttribute('href'),'https://www.asd-ste100.org/STE_faq.html');await page.getByLabel('Custom project instructions',{exact:true}).fill('A project preference, with exact API identifiers.');await f.save();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:'outputs/bl008-guidance-compact.png',fullPage:true});
 await button('Restore built-in defaults').click();await page.keyboard.press('Escape');assert.equal((await f.read()).agentGuidance.overrides.writing_strength_percent,100);
}));
test('newer settings input survives an in-flight save and a cancelled navigation',async()=>fixture(async f=>{
 const {page,button}=f;await button('Edit AI guidance').click();await page.getByLabel('Custom project instructions',{exact:true}).fill('Submitted guidance');let release,seen;const held=new Promise(r=>release=r),started=new Promise(r=>seen=r);
 await page.route('**/api/agent-guidance',async route=>{const response=await route.fetch();assert.equal(response.status(),200);seen();await held;await route.fulfill({response});});
 try{await button('Save AI guidance').click();await started;await page.getByLabel('Custom project instructions',{exact:true}).fill('Newer pending guidance');await f.remote({writing_strength_percent:100});await f.reflected();await f.select(f.other.name);await page.getByRole('heading',{name:'Keep pending AI guidance?'}).waitFor();await button('Keep editing').click();release();await page.getByText('Submitted guidance saved. Your newer input remains unsaved.',{exact:true}).waitFor();assert.equal(await page.getByLabel('Custom project instructions',{exact:true}).inputValue(),'Newer pending guidance');assert.equal(await button('Save AI guidance').isDisabled(),true);assert.equal(await page.getByRole('heading',{name:f.doc().name+'.',exact:true}).count(),1);}finally{release();}
}));
test('finishing an already-running save does not confirm a pending project switch',async()=>fixture(async f=>{
 const {page,button}=f;await button('Edit AI guidance').click();await page.getByLabel('Custom project instructions',{exact:true}).fill('Already saving this guidance');let release,seen;const held=new Promise(r=>release=r),started=new Promise(r=>seen=r);
 await page.route('**/api/agent-guidance',async route=>{const response=await route.fetch();seen();await held;await route.fulfill({response});});
 try{await button('Save AI guidance').click();await started;await f.select(f.other.name);await page.getByRole('heading',{name:'Keep pending AI guidance?'}).waitFor();release();await button('Edit AI guidance').waitFor();assert.equal(await page.getByRole('heading',{name:f.doc().name+'.',exact:true}).count(),1);assert.equal(await page.getByRole('heading',{name:f.other.name+'.',exact:true}).count(),0);}finally{release();}
}));
