import test from 'node:test';
import assert from 'node:assert/strict';
import {acceptRequirements} from './fixtures/accepted-requirements.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_ROOT??'playwright');
const origin=process.env.WONDERWORKS_TEST_URL??'http://127.0.0.1:5173';
if(!['localhost','127.0.0.1'].includes(new URL(origin).hostname))throw Error('Use loopback QA storage.');
async function rest(body){const r=await fetch(origin+'/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();assert.equal(r.status,200,JSON.stringify(d));return d;}
async function fixture(run){
 let doc=await rest({action:'project',name:'BL007 Browser '+Date.now(),prefix:'PB'});
 const read=async()=>doc=await (await fetch(origin+'/api/workspace?project='+doc.id)).json();
 const write=async(action,data={})=>{await read();return doc=await rest({project:doc.id,version:doc.version,action,...data});};
 await write('section',{section:{title:'Core behavior',description:'Proposal authoring checks'}});
 doc=await acceptRequirements(doc,[{section:doc.sections[0].id,title:'Accepted original behavior',description:'Preserve the original accepted requirement.',criteria:['The accepted set remains unchanged.'],priority:'High',status:'Draft',parameters:{speed:5},links:[],tags:['accepted']}],rest);
 await write('proposal',{proposal:{title:'Existing draft destination'}});const destination=doc.proposals[0].id;
 const other=await rest({action:'project',name:'BL007 Other '+Date.now(),prefix:'PB'});
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 await context.addInitScript(()=>{window.browserTools={};Object.defineProperty(document,'modelContext',{value:{registerTool(tool,{signal}){window.browserTools[tool.name]=tool;signal.addEventListener('abort',()=>{if(window.browserTools[tool.name]===tool)delete window.browserTools[tool.name];});return Promise.resolve();}}});});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(7000);
 const reflected=async()=>page.getByText(`Workspace revision ${doc.version} · Durable storage`,{exact:true}).waitFor({timeout:5000});
 const choose=async id=>page.getByLabel('Working requirements',{exact:true}).selectOption(id);
 const edit=async title=>{await page.locator('.requirement-select').first().dblclick();await page.getByRole('textbox',{name:'Title',exact:true}).fill(title);};
 const button=name=>page.getByRole('button',{name,exact:true});
 const save=async(name,stay=true)=>{const pending=page.waitForResponse(r=>r.url().endsWith('/api/proposal-authoring')&&r.request().method()==='POST');await button(name).click();const response=await pending;assert.equal(response.status(),200,await response.text());await read();if(stay)await reflected();};
 try{
  await page.goto(origin);await page.getByRole('combobox',{name:'Current project',exact:true}).click();await page.getByRole('option',{name:doc.name,exact:true}).click();await reflected();
  await run({page,context,read,write,doc:()=>doc,destination,other,reflected,choose,edit,button,save});assert.deepEqual(errors,[]);
 }finally{await browser.close();}
}
test('accepted editor cancels losslessly, resolves existing staged differences, and saves directly in a Draft',async()=>fixture(async f=>{
 const {page,button,destination}=f;const accepted=structuredClone(f.doc().requirements);
 await f.write('proposal_requirement',{id:destination,requirement:{...accepted[0],title:'Existing staged title'}});await f.reflected();
 await f.edit('Pending user title');await button('Save to proposal').click();await page.getByLabel('Destination proposal',{exact:true}).selectOption('new');await page.getByLabel('Proposal title',{exact:true}).fill('Never created');await button('Cancel destination selection').click();assert.equal(await page.getByLabel('Title',{exact:true}).inputValue(),'Pending user title');assert.equal((await f.read()).proposals.length,2);
 await button('Choose destination').click();await page.getByLabel('Destination proposal',{exact:true}).selectOption(destination);assert.equal(await button('Stage in proposal').isDisabled(),true);await button('Use my pending values in this proposal').click();await f.save('Stage in proposal');
 assert.equal(await page.getByLabel('Working requirements',{exact:true}).inputValue(),destination);assert.deepEqual(f.doc().requirements,accepted);assert.equal(f.doc().proposals[0].requirements[0].title,'Pending user title');
 await f.edit('Second staged edit');await f.save('Save to proposal');assert.equal(f.doc().proposals[0].requirements[0].revision,2);assert.deepEqual(f.doc().requirements,accepted);
 await page.getByRole('tab',{name:/Changes/}).click();await page.locator('.proposal-diff').getByText('Second staged edit',{exact:true}).first().waitFor();await page.getByRole('tab',{name:/Requirements/}).click();assert.equal(await page.getByLabel('Working requirements',{exact:true}).inputValue(),destination);
 await f.choose('');await page.locator('.requirement-row').getByRole('heading',{name:'Accepted original behavior'}).waitFor();await f.choose(destination);await page.reload();await page.getByRole('combobox',{name:'Current project',exact:true}).click();await page.getByRole('option',{name:f.doc().name,exact:true}).click();await f.choose(destination);await page.locator('.requirement-row').getByRole('heading',{name:'Second staged edit'}).waitFor();
}));
test('live destination updates retain selection/title/input and closed targets require explicit retargeting',async()=>fixture(async f=>{
 const {page,button,destination}=f;
 await f.edit('Retained pending values');await button('Save to proposal').click();await page.getByLabel('Destination proposal',{exact:true}).selectOption('new');await page.getByLabel('Proposal title',{exact:true}).fill('Retained proposal title');await page.getByLabel('Reason for this change').fill('Retained proposal reason');await page.getByLabel('Proposal title',{exact:true}).focus();
 await f.write('section',{section:{title:'Remote metadata change',description:''}});await f.reflected();assert.equal(await page.getByLabel('Proposal title',{exact:true}).inputValue(),'Retained proposal title');assert.equal(await page.getByLabel('Reason for this change').inputValue(),'Retained proposal reason');assert.equal(await page.getByLabel('Proposal title',{exact:true}).evaluate(el=>el===document.activeElement),true);assert.equal(await button('Create proposal and stage').isDisabled(),true);await button('I reviewed latest; keep my input').click();
 await page.getByLabel('Destination proposal',{exact:true}).selectOption(destination);await f.write('proposal_rebase',{id:destination,resolutions:{}});await f.write('proposal_requirement',{id:destination,requirement:{...f.doc().requirements[0],title:'Remote staged content'}});await f.write('proposal_submit',{id:destination});await f.reflected();assert.equal(await page.getByLabel('Destination proposal',{exact:true}).inputValue(),destination);assert.equal(await button('Stage in proposal').isDisabled(),true);await page.getByText(/is Proposed and cannot receive edits/).waitFor();
 await page.getByLabel('Destination proposal',{exact:true}).selectOption('new');assert.equal(await page.getByLabel('Proposal title',{exact:true}).inputValue(),'Retained proposal title');await button('I reviewed latest; keep my input').click();await f.save('Create proposal and stage');assert.equal(f.doc().proposals[0].requirements[0].title,'Retained pending values');assert.equal(f.doc().proposals.find(p=>p.id===destination).status,'Proposed');assert.equal(f.doc().requirements[0].title,'Accepted original behavior');
}));
test('uncertain atomic creation replays the identical request after live refresh without duplicates',async()=>fixture(async f=>{
 const {page,button}=f;await f.edit('One atomic pending edit');await button('Save to proposal').click();await page.getByLabel('Destination proposal',{exact:true}).selectOption('new');await page.getByLabel('Proposal title',{exact:true}).fill('One atomic proposal');const before=structuredClone(f.doc());const attempts=[];let first=true;
 await page.route('**/api/proposal-authoring',async route=>{attempts.push(route.request().postDataJSON());if(first){first=false;const r=await route.fetch();assert.equal(r.status(),200,await r.text());await route.abort('failed');}else await route.continue();});
 await button('Create proposal and stage').click();await page.locator('.destination-dialog').getByRole('button',{name:'Retry original save'}).waitFor();await f.read();await f.reflected();await page.locator('.destination-dialog').getByRole('button',{name:'Retry original save'}).click();await page.locator('.requirement-editor').waitFor({state:'hidden'});assert.deepEqual(attempts[0],attempts[1]);assert.equal(f.doc().version,before.version+1);assert.equal(f.doc().proposals.length,before.proposals.length+1);assert.equal(f.doc().history.length,before.history.length+1);assert.deepEqual(f.doc().requirements,before.requirements);
}));
test('input typed during a held save survives a newer read and an older save response',async()=>fixture(async f=>{
 const {page,button,destination}=f;await f.choose(destination);await f.edit('Submitted title');let release,seen;const held=new Promise(r=>release=r),started=new Promise(r=>seen=r);
 await page.route('**/api/proposal-authoring',async route=>{const result=await route.fetch();assert.equal(result.status(),200);seen();await held;await route.fulfill({response:result});});
 await button('Save to proposal').click();await started;await page.getByLabel('Title',{exact:true}).fill('Newer unsaved title');await f.write('section',{section:{title:'After the saved edit',description:''}});await f.reflected();release();await page.getByText(/Your newer input is still here/).waitFor();assert.equal(await page.getByLabel('Title',{exact:true}).inputValue(),'Newer unsaved title');assert.equal(await button('Save to proposal').isDisabled(),true);assert.equal(f.doc().proposals[0].requirements[0].title,'Submitted title');await page.unroute('**/api/proposal-authoring');await button('I reviewed latest; keep my input').click();await f.save('Save to proposal');assert.equal(f.doc().proposals[0].requirements[0].title,'Newer unsaved title');
}));
test('context and project switches offer save/discard/cancel with original edits preserved',async()=>fixture(async f=>{
 const {page,button,destination}=f;await f.choose(destination);await f.edit('Pending context switch');await page.getByLabel('Working requirements',{exact:true}).selectOption('');await page.getByRole('heading',{name:'Keep your pending requirement?'}).waitFor();await page.getByRole('dialog').filter({hasText:'Keep your pending requirement?'}).getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await page.getByLabel('Working requirements',{exact:true}).inputValue(),destination);assert.equal(await page.getByLabel('Title',{exact:true}).inputValue(),'Pending context switch');
 await page.getByLabel('Working requirements',{exact:true}).selectOption('');await button('Discard').click();assert.equal(await page.getByLabel('Working requirements',{exact:true}).inputValue(),'');
 await f.edit('Saved before switching project');await page.getByRole('combobox',{name:'Current project',exact:true}).click();await page.getByRole('option',{name:f.other.name,exact:true}).click();await button('Save to a proposal').click();await page.getByLabel('Destination proposal',{exact:true}).selectOption(destination);await f.save('Stage in proposal',false);await page.getByRole('heading',{name:f.other.name+'.',exact:true}).waitFor();assert.equal(await page.getByLabel('Working requirements',{exact:true}).inputValue(),'');assert.equal(f.doc().proposals[0].requirements[0].title,'Saved before switching project');
}));
test('browser tools require an explicit Draft; compact keyboard flow and staged filtering remain usable',async()=>fixture(async f=>{
 const {page,destination}=f;
 const call=(name,input={})=>page.evaluate(async({name,input})=>{try{return {result:await window.browserTools[name].execute(input)}}catch(e){return {error:e.message}}},{name,input});
 await call('read_requirements');assert.match((await call('save_requirements',{requirements:[f.doc().requirements[0]]})).error,/proposal/i);
 await call('read_requirements');const r=await call('save_requirements',{proposal_id:destination,requirements:[{...f.doc().requirements[0],title:'Browser staged behavior',tags:['browser-only']}]});assert.ok(!r.error,JSON.stringify(r));await f.read();await f.reflected();assert.equal(f.doc().requirements[0].title,'Accepted original behavior');await f.choose(destination);await page.getByRole('textbox',{name:'Search requirements'}).fill('browser-only');assert.equal(await page.locator('.requirement-row').count(),1);await f.choose('');assert.equal(await page.locator('.requirement-row').count(),0);await f.choose(destination);await page.getByRole('textbox',{name:'Search requirements'}).fill('');
 await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:'reduce'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.getByLabel('Working requirements',{exact:true}).focus();await page.keyboard.press('Home');await page.keyboard.press('Enter');await f.choose(destination);await page.locator('.requirement-select').first().click();await page.getByRole('button',{name:'Edit PB-001',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Compact keyboard pending');await page.getByRole('button',{name:'Choose destination',exact:true}).click();await page.getByLabel('Destination proposal',{exact:true}).selectOption('new');await page.getByLabel('Destination proposal',{exact:true}).focus();await page.keyboard.press('Tab');assert.equal(await page.getByLabel('Proposal title',{exact:true}).evaluate(el=>el===document.activeElement),true);await page.keyboard.type('Keyboard destination');await page.screenshot({path:'outputs/bl007-compact-destination.png',fullPage:true});assert.ok(await page.locator('.destination-dialog').evaluate(el=>el.scrollWidth<=el.clientWidth));
}));
test('selected working sets receive deletion/restore/stale/closure updates without overlay or retargeting',async()=>fixture(async f=>{
 const {page,destination,button}=f;await f.choose(destination);await page.locator('.requirement-select').first().click();
 await f.write('proposal_delete',{id:destination,requirementId:'PB-001'});await f.reflected();assert.equal(await page.getByLabel('Working requirements',{exact:true}).inputValue(),destination);assert.equal(await page.locator('.requirement-row').count(),0);await page.getByText(/selected requirement is no longer/).waitFor();
 await f.write('proposal_restore',{id:destination,requirementId:'PB-001'});await f.reflected();assert.equal(await page.locator('.requirement-row').count(),1);
 const {id,revision,...fields}=f.doc().requirements[0];await acceptRequirements(f.doc(),[{...fields,title:'Independent accepted addition',tags:['new-accepted']}],rest);await f.read();await f.reflected();assert.equal(await page.locator('.requirement-row').count(),1);assert.equal(f.doc().requirements.length,2);assert.match(await page.locator('.working-context').innerText(),/Stale/);assert.equal(f.doc().proposals.find(p=>p.id===destination).requirements.length,1);
 await f.write('proposal_rebase',{id:destination,resolutions:{}});await f.write('proposal_requirement',{id:destination,requirement:{...f.doc().requirements[0],title:'Will be rejected'}});await f.write('proposal_submit',{id:destination});await f.reflected();assert.equal(await button('New requirement').isDisabled(),true);await f.write('proposal_review',{id:destination,review:{decision:'reject'}});await f.reflected();assert.equal(await page.getByLabel('Working requirements',{exact:true}).inputValue(),destination);await button('Return to latest accepted requirements').click();assert.equal(await page.getByLabel('Working requirements',{exact:true}).inputValue(),'');assert.equal(await page.locator('.requirement-row').count(),2);assert.equal(f.doc().requirements[0].title,'Accepted original behavior');
}));
test('uncommitted tag input is protected and opening another item starts a fresh bound editor',async()=>fixture(async f=>{
 const {page,button,destination}=f;await f.choose(destination);await page.locator('.requirement-select').first().dblclick();await page.getByRole('combobox',{name:'Tags',exact:true}).fill('pending-tag');await page.getByLabel('Working requirements',{exact:true}).selectOption('');await page.getByRole('heading',{name:'Keep your pending requirement?'}).waitFor();await page.getByRole('dialog').filter({hasText:'Keep your pending requirement?'}).getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await page.getByRole('combobox',{name:'Tags',exact:true}).inputValue(),'pending-tag');await button('Cancel').click();await button('Discard').click();await page.locator('.requirement-select').first().dblclick();await button('New requirement').click();assert.equal(await page.getByLabel('Title',{exact:true}).inputValue(),'');await page.getByRole('heading',{name:'New requirement',exact:true}).waitFor();
}));
