import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {acceptRequirements} from './fixtures/accepted-requirements.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_ROOT??'playwright');
const origin=process.env.WONDERWORKS_TEST_URL??'http://127.0.0.1:5173',mcpOrigin=process.env.WONDERWORKS_MCP_URL??origin;
for(const url of [origin,mcpOrigin])if(!['localhost','127.0.0.1'].includes(new URL(url).hostname))throw Error('Use loopback QA storage.');
const examples=JSON.parse(await readFile(new URL('./fixtures/bl012-reading.json',import.meta.url)));
const markdown='## Readable heading 👩🏽‍💻\n\n**Strong** and *emphasis* with [safe link](https://example.com).\n\n> Quoted content\n\n1. First\n2. Second\n\n| Identifier | Comparison |\n|---|---|\n| `snake_case` | x < y |\n\n```js\nconst snake_case = "<literal>";\n```\n\n'+('Complete ordinary words 👨‍👩‍👧‍👦 é remain intact. '.repeat(20))+'\nFinal complete body.';
const plain='  <literal> snake_case x < y **stars** [link](literal)\n\tmeaningful spaces  \n';
const html='<h2>Safe HTML heading</h2><p><strong>Emphasis</strong> snake_case &lt; comparison</p><table><tr><th>Cell</th></tr><tr><td>Value</td></tr></table><script>window.bl012Attack=1</script><img src="https://bl012-attack.example/a" onerror="window.bl012Attack=2">';
async function rest(body){const r=await fetch(origin+'/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();assert.equal(r.status,200,JSON.stringify(d));return d;}
test('BL012 complete reading and direct Changes authoring with independent MCP persistence',async t=>{
 let doc=await rest({action:'project',name:'BL012 reading '+Date.now(),prefix:'RD'});
 const read=async()=>doc=await(await fetch(origin+'/api/workspace?project='+doc.id)).json();
 const write=async(action,data={})=>{await read();return doc=await rest({project:doc.id,version:doc.version,action,...data});};
 await write('section',{section:{title:'Readable specification',description:'Desktop and compact reading checks'}});
 const req=(title,description,extra={})=>({section:doc.sections[0].id,title,description,criteria:['First ordered criterion','Second ordered criterion'],parameters:{snake_case:42},tags:['reading'],body_format:'markdown',...extra});
 const guide=ex=>req(ex.title,ex.description,{kind:'information',criteria:[],parameters:{},diagrams:ex.diagrams??[],summarizes:[{requirement_id:'RD-001'}],diagram_mappings:(ex.diagram_mappings??[]).map(m=>({...m,requirement_ids:['RD-001']}))});
 doc=await acceptRequirements(doc,[req('Structured Markdown',markdown),req('Semantic HTML',html,{body_format:'html'}),req('Literal plain text',plain,{body_format:'plain_text'}),req('Table-led guidance',examples[0].description,{links:['RD-001']}),...Array.from({length:22},(_,i)=>req('Long-list requirement '+i,'A complete body for result '+i+'.')),...examples.slice(1).map(guide),req('Diagram only','',{diagrams:[{id:'only',language:'dot',source:'digraph G {a[label="Begin"];a->b[label="Continue"]}',title:'Diagram-only overview',alt:'Begin connects to the next state.',position:0}]})],rest);
 await write('proposal',{proposal:{title:'Historical applied change'}});let historical=doc.proposals[0].id;await write('proposal_requirement',{id:historical,requirement:{...doc.requirements[20],title:'Applied historical title'}});await write('proposal_submit',{id:historical});await write('proposal_review',{id:historical,review:{decision:'apply'}});
 await write('proposal',{proposal:{title:'Historical rejected change'}});const rejected=doc.proposals[0].id;await write('proposal_requirement',{id:rejected,requirement:{...doc.requirements[1],body_format:'markdown',description:'## Rejected saved body\n\nRejected source remains historical.'}});await write('proposal_submit',{id:rejected});await write('proposal_review',{id:rejected,review:{decision:'reject'}});
 await write('proposal',{proposal:{title:'Unrelated Draft stays unchanged'}});const other=doc.proposals[0].id;
 await write('proposal',{proposal:{title:'Direct Changes destination'}});const destination=doc.proposals[0].id;
 await write('proposal_requirement',{id:destination,requirement:{...doc.requirements[0],description:markdown+'\nSaved staged body.'}});
 await write('proposal_requirement',{id:destination,requirement:{...doc.requirements[1],body_format:'markdown',description:'## Markdown after HTML\n\nStaged body changes its format.'}});
 await write('proposal_requirement',{id:destination,requirement:{...doc.requirements[2],description:plain+'  '}});
 await write('proposal_requirement',{id:destination,requirement:{...doc.requirements[3],criteria:['Updated criterion without body change']}});
 await write('proposal_delete',{id:destination,requirementId:'RD-005'});
 await write('proposal_requirement',{id:destination,requirement:req('Added direct requirement',markdown)});const added=doc.proposals[0].requirements.at(-1).id;
 await write('proposal_requirement',{id:destination,requirement:{...guide(examples[1]),title:'Added Information guide'}});const info=doc.proposals[0].requirements.at(-1).id;
 const frozen=structuredClone({requirements:doc.requirements,requirementsVersion:doc.requirementsVersion,baselines:doc.baselines,evidence:doc.evidence,other:doc.proposals.find(p=>p.id===other)});
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})}),context=await browser.newContext({viewport:{width:1500,height:1100}}),page=await context.newPage(),errors=[],requests=[];
 page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
 const cookie=(await fetch(mcpOrigin+'/signin-with-chatgpt?return_to=/',{redirect:'manual'})).headers.get('set-cookie').split(';')[0];
 const mcp=async(name,args)=>{const response=await fetch(mcpOrigin+'/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream','MCP-Protocol-Version':'2025-11-25',Cookie:cookie},body:JSON.stringify({jsonrpc:'2.0',id:crypto.randomUUID(),method:'tools/call',params:{name,arguments:args}})});const v=(await response.json()).result;assert.ok(!v.isError,JSON.stringify(v));return v.structuredContent;};
 const proposal=async()=> (await mcp('get_proposal',{project_id:doc.id,proposal_id:destination})).proposal;
 const button=name=>page.getByRole('button',{name,exact:true}),card=id=>page.locator('#proposal-item-'+id),reader=()=>page.locator('.compact-reader'),editor=()=>page.locator('.requirement-editor');
 const reflected=async()=>page.getByText(`Workspace revision ${doc.version} · Durable storage`,{exact:true}).waitFor({state:'attached',timeout:5000});
 const select=async()=>{await page.goto(origin);await page.getByRole('combobox',{name:'Current project',exact:true}).click();await page.getByRole('option',{name:doc.name,exact:true}).click();await reflected();};
 const changes=async(id=destination)=>{await page.getByRole('tab',{name:/Changes/}).click();await page.locator('.proposal-list-item').filter({has:page.getByText(id,{exact:true})}).click();};
 const save=async()=>{const response=page.waitForResponse(r=>r.url().endsWith('/api/proposal-authoring')&&r.request().method()==='POST');await button('Save to proposal').click();assert.equal((await response).status(),200);await editor().waitFor({state:'hidden'});await read();await reflected();assert.equal(await page.getByRole('tab',{name:/Changes/}).getAttribute('data-state'),'active');assert.equal(await page.getByLabel('Destination proposal',{exact:true}).count(),0);};
 try{
 await select();
 await t.test('format-aware excerpts and desktop full readers preserve semantic/literal content and contain unsafe HTML',async()=>{
  const first=page.locator('.requirement-row').first();await first.locator('.requirement-excerpt').filter({hasText:'Readable heading'}).waitFor();const excerpt=await first.locator('.requirement-excerpt').textContent();assert.ok(!/\|---|```|\[safe link\]|##/.test(excerpt));assert.match(excerpt,/snake_case/);assert.match(excerpt,/More|Readable/);await first.getByText('More content · Read full item and source',{exact:true}).waitFor();
  assert.equal(await page.locator('.requirement-excerpt').nth(2).textContent(),plain);
  await page.locator('.requirement-select').first().click();const view=page.locator('.inspector');await view.getByText(/Final complete body/).first().waitFor();assert.equal(await view.locator('.semantic-body table').count(),1);assert.equal(await view.locator('.semantic-body a').getAttribute('href'),'https://example.com');await view.getByText('Original body source · markdown',{exact:true}).click();assert.equal(await view.locator('.rich-content details pre').textContent(),markdown);
  await page.locator('.requirement-select').nth(1).click();await view.getByRole('heading',{name:'Safe HTML heading'}).waitFor();assert.equal(await view.locator('script,img').count(),0);assert.equal(await page.evaluate(()=>window.bl012Attack),undefined);assert.ok(!requests.some(r=>r.includes('bl012-attack.example')));
  await page.locator('.requirement-select').last().click();await view.locator('figure svg').waitFor();assert.match(await page.locator('.requirement-excerpt').last().textContent(),/Diagram-only overview.*Begin connects/s);
 });
 await t.test('compact reader opens immediately from a long list and returns focus, filters and scroll without writes',async()=>{
  const before=doc.version;await page.setViewportSize({width:390,height:844});await reader().getByRole('button',{name:'Back to results'}).click();await reader().waitFor({state:'hidden'});await page.getByLabel('Search requirements').fill('Table-led');const trigger=page.locator('.requirement-select').first();await trigger.scrollIntoViewIfNeeded();const y=await page.evaluate(()=>scrollY);await trigger.click();await reader().getByText('Updated criterion without body change',{exact:true}).waitFor({state:'hidden'});await reader().getByText('First ordered criterion',{exact:true}).waitFor();assert.match(await reader().locator('.readonly-requirement>pre').textContent(),/snake_case/);await reader().locator('.semantic-body table').waitFor();await reader().getByRole('button',{name:'RD-001 · Structured Markdown',exact:true}).click();await reader().getByText(/Final complete body/).first().waitFor();await reader().getByText('Original body source · markdown',{exact:true}).click();assert.equal(await reader().locator('.rich-content details pre').textContent(),markdown);await reader().getByRole('button',{name:'Back to results'}).click();await reader().waitFor({state:'hidden'});assert.equal(await page.evaluate(()=>document.activeElement.id),'requirement-select-RD-004');assert.ok(Math.abs(await page.evaluate(()=>scrollY)-y)<3);assert.equal(await page.getByLabel('Search requirements').inputValue(),'Table-led');assert.equal((await read()).version,before);
  await page.getByLabel('Search requirements').fill('');await page.locator('.requirement-select').nth(26).click();await reader().locator('figure svg').first().waitFor();await page.screenshot({path:'outputs/bl012-compact-reader.png',animations:'disabled'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await reader().getByRole('button',{name:'Back to results'}).click();await reader().waitFor({state:'hidden'});await page.setViewportSize({width:1500,height:1100});
 });
 await t.test('Changes defaults to complete rendered before/after, exact source diffs and historical outcome labels',async()=>{
  await changes();await card('RD-001').getByText(/Saved staged body/).first().waitFor();await card('RD-002').getByRole('heading',{name:'Safe HTML heading'}).waitFor();await card('RD-002').getByRole('heading',{name:'Markdown after HTML'}).waitFor();await card('RD-004').locator('.rendered-comparison .semantic-body table').first().waitFor();assert.equal(await card('RD-004').locator('.rendered-comparison .semantic-body table').count(),2);await card(added).getByText('Not present · Added item',{exact:true}).waitFor();await card('RD-005').getByText('Not present · Deleted item',{exact:true}).waitFor();assert.equal(await card('RD-005').getByRole('button',{name:'Edit RD-005',exact:true}).count(),0);await card('RD-005').getByRole('button',{name:'Restore RD-005',exact:true}).waitFor();
  await card('RD-003').getByText('Source differences · RD-003',{exact:true}).click();assert.equal(await card('RD-003').locator('.diff-before pre').textContent(),plain);assert.equal(await card('RD-003').locator('.diff-after pre').textContent(),plain+'  ');
  await changes(rejected);await card('RD-002').getByRole('heading',{name:'Rejected saved body'}).waitFor();assert.match(await card('RD-002').textContent(),/Rejected · Historical/);assert.equal(await card('RD-002').getByRole('button',{name:'Edit RD-002',exact:true}).count(),0);
  await changes(historical);assert.match(await page.locator('.proposal-diff').textContent(),/Applied · Saved/);assert.equal(await page.locator('.proposal-diff').getByRole('button',{name:/^Edit RD-/}).count(),0);await changes();await page.screenshot({path:'outputs/bl012-changes.png',animations:'disabled'});
 });
 await t.test('direct added/edited/Information edits retain exact untouched fields and stay in Changes with MCP readback',async()=>{
  for(const [index,id] of ['RD-001',added,info].entries()){
   const before=(await proposal()).requirements.find(r=>r.id===id);const action=card(id).getByRole('button',{name:'Edit '+id,exact:true});if(index===1){await action.focus();await page.keyboard.press('Enter');}else await action.click();await editor().waitFor();assert.equal(await page.getByLabel('Description',{exact:true}).inputValue(),before.description);await editor().getByText(new RegExp(destination+' · Direct Changes destination')).first().waitFor();const exact=before.description+'\n\nSaved direct '+id+' 👩🏽‍💻  \n';await page.getByLabel('Description',{exact:true}).fill(exact);if(index!==2)await page.getByLabel('Acceptance criteria',{exact:false}).fill('First updated outcome\nSecond updated outcome');await button('Preview').click();await editor().locator('.rich-content .semantic-body').getByText('Saved direct '+id+' 👩🏽‍💻',{exact:false}).first().waitFor();await button('Source').click();assert.equal(await page.getByLabel('Description',{exact:true}).inputValue(),exact);await save();await card(id).getByText('Saved direct '+id+' 👩🏽‍💻',{exact:false}).first().waitFor();const after=(await proposal()).requirements.find(r=>r.id===id);assert.equal(after.id,id);assert.equal(after.description,exact);assert.equal(after.revision,before.revision);for(const field of ['body_format','diagrams','tags','parameters','links','summarizes','diagram_mappings'])assert.deepEqual(after[field],before[field]);if(index!==2)assert.deepEqual(after.criteria,['First updated outcome','Second updated outcome']);await card(id).getByText('Source differences · '+id,{exact:true}).click();assert.match(await card(id).locator('.diff-after').allTextContents().then(x=>x.join('')),/Saved direct/);
  }
  const latest=await read();assert.deepEqual({requirements:latest.requirements,requirementsVersion:latest.requirementsVersion,baselines:latest.baselines,evidence:latest.evidence,other:latest.proposals.find(p=>p.id===other)},frozen);await select();await changes();await card(info).getByText('Saved direct '+info+' 👩🏽‍💻',{exact:false}).first().waitFor();
 });
 await t.test('clean cancel, dirty retention/discard, detail-reader and batch edits preserve focus and compact controls',async()=>{
  const id=added,before=(await proposal()).requirements.find(r=>r.id===id);let trigger=card(id).getByRole('button',{name:'Edit '+id,exact:true});await trigger.click();await editor().getByRole('button',{name:'Cancel',exact:true}).click();await editor().waitFor({state:'hidden'});assert.ok(await trigger.evaluate(el=>document.activeElement===el));await trigger.click();await page.getByLabel('Title',{exact:true}).fill('Discard this title');await editor().getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('dialog',{name:'Keep your pending requirement?'}).getByRole('button',{name:'Cancel',exact:true}).click();assert.equal(await page.getByLabel('Title',{exact:true}).inputValue(),'Discard this title');await editor().getByRole('button',{name:'Cancel',exact:true}).click();await button('Discard').click();await editor().waitFor({state:'hidden'});assert.deepEqual((await proposal()).requirements.find(r=>r.id===id),before);assert.ok(await trigger.evaluate(el=>document.activeElement===el));
  await page.setViewportSize({width:390,height:844});await card(id).getByRole('button',{name:'Read '+id,exact:true}).click();await page.locator('.snapshot-reader').getByRole('button',{name:'Edit '+id,exact:true}).click();await editor().waitFor();await page.getByLabel('Title',{exact:true}).fill('Compact direct saved title');await button('Preview').click();await page.screenshot({path:'outputs/bl012-compact-editor.png',animations:'disabled'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await save();await card(id).getByRole('heading',{name:'Compact direct saved title'}).waitFor();await page.setViewportSize({width:1500,height:1100});await button('Edit requirement batch').click();await button('Propose edit '+id).click();await page.getByLabel('Title',{exact:true}).fill('Batch still stays in Changes');await save();await card(id).getByRole('heading',{name:'Batch still stays in Changes'}).waitFor();
 });
 await t.test('remote edits and submission retain dirty source/destination and require explicit reconciliation',async()=>{
  await card(added).getByRole('button',{name:'Edit '+added,exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Pending through remote changes');let p=await proposal(),r=p.requirements.find(r=>r.id===added);await read();const {id,revision,status,...fields}=r;await mcp('stage_proposal_changes',{project_id:doc.id,proposal_id:destination,expected_workspace_version:doc.version,idempotency_key:crypto.randomUUID(),operations:[{op:'edit',requirement_id:id,requirement:{...fields,title:'Remote title'}}]});await read();await reflected();assert.equal(await page.getByLabel('Title',{exact:true}).inputValue(),'Pending through remote changes');assert.ok(await button('Save to proposal').isDisabled());await editor().getByRole('button',{name:'I reviewed latest; keep my input',exact:true}).click();assert.ok(await button('Save to proposal').isDisabled());await button('Use my pending values in this proposal').click();await save();
  await card(added).getByRole('button',{name:'Edit '+added,exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Pending after submission');await read();await mcp('submit_proposal',{project_id:doc.id,proposal_id:destination,expected_workspace_version:doc.version,idempotency_key:crypto.randomUUID()});await read();await reflected();assert.equal(await page.getByLabel('Title',{exact:true}).inputValue(),'Pending after submission');await editor().getByText(new RegExp(destination+' is Proposed')).waitFor();assert.ok(await button('Save to proposal').isDisabled());await editor().getByRole('button',{name:'Cancel',exact:true}).click();await button('Discard').click();await editor().waitFor({state:'hidden'});assert.equal(await page.locator('.proposal-diff').getByRole('button',{name:/^Edit RD-/}).count(),0);await page.locator('.proposal-detail .edit-conflict').getByRole('button',{name:'I reviewed latest; keep my input',exact:true}).click();await button('Request changes').click();await read();await reflected();await card(added).getByRole('button',{name:'Edit '+added,exact:true}).waitFor();
 });
 await t.test('validation failures and uncertain saves retain input and retry only the original atomic request',async()=>{
  await card(added).getByRole('button',{name:'Edit '+added,exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Recovered direct save');await editor().getByText('Specified parameters',{exact:true}).click();await page.getByLabel('Requirement parameters JSON').fill('not json');await button('Save to proposal').click();await editor().getByRole('alert').waitFor();assert.equal(await page.getByLabel('Title',{exact:true}).inputValue(),'Recovered direct save');await page.getByLabel('Requirement parameters JSON').fill('{"snake_case":42}');
  let first=true;const attempts=[],version=(await read()).version;await page.route('**/api/proposal-authoring',async route=>{attempts.push(route.request().postDataJSON());if(first){first=false;const response=await route.fetch();assert.equal(response.status(),200,await response.text());await route.abort('failed');}else await route.continue();});await button('Save to proposal').click();await button('Retry original save').waitFor();assert.equal(await page.getByLabel('Title',{exact:true}).inputValue(),'Recovered direct save');await button('Retry original save').click();await editor().waitFor({state:'hidden'});await page.unroute('**/api/proposal-authoring');assert.deepEqual(attempts[0],attempts[1]);assert.equal((await read()).version,version+1);assert.equal((await proposal()).requirements.find(r=>r.id===added).title,'Recovered direct save');await card(added).getByRole('heading',{name:'Recovered direct save'}).waitFor();
 });
 await t.test('remote deletion blocks a dirty direct edit until explicit Restore',async()=>{
  await card('RD-002').getByRole('button',{name:'Edit RD-002',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Retain after deletion');await read();await mcp('stage_proposal_changes',{project_id:doc.id,proposal_id:destination,expected_workspace_version:doc.version,idempotency_key:crypto.randomUUID(),operations:[{op:'delete',requirement_id:'RD-002'}]});await read();await reflected();await editor().getByText(/The source requirement was removed/).waitFor();assert.equal(await page.getByLabel('Title',{exact:true}).inputValue(),'Retain after deletion');assert.ok(await button('Save to proposal').isDisabled());await editor().getByRole('button',{name:'Cancel',exact:true}).click();await button('Discard').click();await editor().waitFor({state:'hidden'});
  assert.equal(await card('RD-002').getByRole('button',{name:'Edit RD-002',exact:true}).count(),0);await page.locator('.proposal-detail>.edit-conflict').getByRole('button',{name:'I reviewed latest; keep my input',exact:true}).click();await card('RD-002').getByRole('button',{name:'Restore RD-002',exact:true}).click();await read();await reflected();assert.ok((await proposal()).requirements.some(r=>r.id==='RD-002'));
 });
 await t.test('offline direct save retains its destination/input and retries once after connectivity returns',async()=>{
  await card(added).getByRole('button',{name:'Edit '+added,exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Recovered after offline');const before=(await read()).version;await context.setOffline(true);await button('Save to proposal').click();await button('Retry original save').waitFor();assert.equal(await page.getByLabel('Title',{exact:true}).inputValue(),'Recovered after offline');await editor().getByText(new RegExp(destination+' · Direct Changes destination')).first().waitFor();await context.setOffline(false);await button('Retry original save').click();await editor().waitFor({state:'hidden'});assert.equal((await read()).version,before+1);assert.equal((await proposal()).requirements.find(r=>r.id===added).title,'Recovered after offline');
 });
 await t.test('acknowledging an older own save cannot silently authorize a newer remote review',async()=>{
  await card(added).getByRole('button',{name:'Edit '+added,exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('Own acknowledged title');
  await page.route('**/api/proposal-authoring',async route=>{const response=await route.fetch();assert.equal(response.status(),200);await read();const r=(await proposal()).requirements.find(r=>r.id==='RD-003'),{id,revision,status,...fields}=r;await mcp('stage_proposal_changes',{project_id:doc.id,proposal_id:destination,expected_workspace_version:doc.version,idempotency_key:crypto.randomUUID(),operations:[{op:'edit',requirement_id:id,requirement:{...fields,title:'Newer remote review context'}}]});await read();await reflected();await route.fulfill({response});});
  await save();await page.unroute('**/api/proposal-authoring');await page.locator('.proposal-detail>.edit-conflict').getByRole('button',{name:'I reviewed latest; keep my input',exact:true}).waitFor();assert.ok(await button('Submit for review').isDisabled());await card('RD-003').getByRole('heading',{name:'Newer remote review context'}).waitFor();
 });
 assert.deepEqual(errors,[]);console.log('BL012_QA_PROJECT',doc.id);await writeFile('outputs/bl012-browser-result.json',JSON.stringify({project_id:doc.id,proposal_id:destination,workspace_version:doc.version,independent_mcp_readback:true},null,2));
 }finally{await browser.close();}
});
