import test from 'node:test';
import assert from 'node:assert/strict';
import {acceptRequirements} from './fixtures/accepted-requirements.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_ROOT??'playwright');
const origin=process.env.WONDERWORKS_TEST_URL??'http://127.0.0.1:5173';
if(!['localhost','127.0.0.1'].includes(new URL(origin).hostname))throw Error('Use loopback QA storage.');
async function rest(body){const r=await fetch(origin+'/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();assert.equal(r.status,200,JSON.stringify(d));return d;}
async function fixture(run,init){
 let doc=await rest({action:'project',name:'BL009 Browser '+Date.now(),prefix:'RB'});
 const read=async()=>doc=await(await fetch(origin+'/api/workspace?project='+doc.id)).json();
 const write=async(action,data={})=>{await read();return doc=await rest({project:doc.id,version:doc.version,action,...data});};
 await write('section',{section:{title:'Content behavior',description:'Rich-content browser checks'}});
 const req=(i,extra={})=>({section:doc.sections[0].id,title:'Source '+i,description:'Source '+i+' remains normative.',criteria:['The testable outcome is observed.'],priority:'High',parameters:{},links:[],...extra});
 doc=await acceptRequirements(doc,Array.from({length:10},(_,i)=>req(i)),rest);
 await write('proposal',{proposal:{title:'Rich-content draft'}});const destination=doc.proposals[0].id;
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
 const context=await browser.newContext({viewport:{width:1500,height:1100}});if(init)await context.addInitScript(init);
 const page=await context.newPage(),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));page.setDefaultTimeout(10000);
 const reflected=async()=>page.getByText(`Workspace revision ${doc.version} · Durable storage`,{exact:true}).waitFor({state:'attached',timeout:5000});
 const choose=async()=>page.getByLabel('Working requirements',{exact:true}).selectOption(destination);
 const button=name=>page.getByRole('button',{name,exact:true});
 const save=async()=>{const pending=page.waitForResponse(r=>r.url().endsWith('/api/proposal-authoring')&&r.request().method()==='POST');await button('Save to proposal').click();const r=await pending;assert.equal(r.status(),200,await r.text());await read();await reflected();};
 try{await page.goto(origin);await page.getByRole('combobox',{name:'Current project',exact:true}).click();await page.getByRole('option',{name:doc.name,exact:true}).click();await reflected();await choose();await run({page,context,read,write,doc:()=>doc,destination,reflected,button,save,req,requests});assert.deepEqual(errors,[]);}catch(error){console.log('BROWSER_FAILURE_CONTEXT',await page.locator('.inspector').innerText());throw error;}finally{await browser.close();}
}
const sample='## Rich heading 😀\n\n**Strong** and *emphasis* with `code`.\n\n> Quoted content\n\n1. First\n2. Second\n\n| A | B |\n|---|---|\n| One | Two |\n\n```js\nconst literal = `<tag>`;\n```\n\n<a href="https://example.com">Safe link</a>\n';
test('UI round-trips all body formats, source selection, live dirty input and saved preview',async()=>fixture(async f=>{
 const {page,button}=f;
 for(const format of ['markdown','html','plain_text']){
  await page.locator('.requirement-select').first().dblclick();const editor=page.locator('.requirement-editor');await page.getByLabel('Body format',{exact:true}).selectOption(format);await button('Source').click();const source=format==='markdown'?sample:format==='html'?'<h2>Safe HTML 😀</h2>\n<p>  &amp; <em>emphasis</em></p>\n':'  <literal> &amp; 😀\n\n\tkept exactly  \n';await page.getByLabel('Description',{exact:true}).fill(source);
  await page.getByLabel('Description',{exact:true}).evaluate(el=>el.setSelectionRange(3,8));await button('Preview').click();await button('Source').click();assert.deepEqual(await page.getByLabel('Description',{exact:true}).evaluate(el=>[el.selectionStart,el.selectionEnd]),[3,8]);assert.equal(await page.getByLabel('Description',{exact:true}).inputValue(),source);await button('Preview').click();
  if(format==='markdown'){await editor.getByRole('heading',{name:'Rich heading 😀'}).waitFor();assert.equal(await editor.locator('.semantic-body table').count(),1);assert.equal(await editor.locator('.semantic-body strong').textContent(),'Strong');}
  if(format==='plain_text')assert.equal(await editor.locator('.plain-body').textContent(),source);
  await f.write('section',{section:{title:'Live '+format,description:''}});await f.reflected();await button('Source').click();assert.equal(await page.getByLabel('Description',{exact:true}).inputValue(),source);assert.equal(await button('Save to proposal').isDisabled(),true);await button('I reviewed latest; keep my input').click();await f.save();assert.equal(f.doc().proposals[0].requirements[0].description,source);assert.equal(f.doc().proposals[0].requirements[0].body_format,format);await page.locator('.inspector .rich-content').waitFor();
 }
}));
test('multiple Mermaid and DOT diagrams render with text alternatives, source, zoom and safe failures',async()=>fixture(async f=>{
 const sources=[['mermaid','flowchart TD\n subgraph G[Group]\n A[Start] -->|yes| B{Done}\n end'],['mermaid','sequenceDiagram\n participant A as Alice\n A->>B: Request\n B-->>A: Result'],['mermaid','stateDiagram-v2\n [*] --> Ready\n Ready --> Done: go'],['dot','digraph G {a[label="Start"];a->b[label="next"]}'],['dot','graph G {a--b}'],['dot','digraph G {subgraph cluster_one {label="Group";a;b;}a->b}']];
 const diagrams=sources.map(([language,source],i)=>({id:'block-'+i,language,source,title:'Diagram '+i,alt:'Text alternative '+i,position:0}));
 await f.write('proposal_requirement',{id:f.destination,requirement:{...f.doc().requirements[0],description:sample,body_format:'markdown',diagrams}});await f.reflected();await f.page.locator('.requirement-select').first().click();const view=f.page.locator('.inspector');
 await view.locator('figure svg').nth(5).waitFor();assert.equal(await view.locator('figure svg').count(),6);assert.equal(await view.locator('.error-box').count(),0);
 for(let i=0;i<6;i++)await view.getByText('Text alternative '+i,{exact:true}).waitFor();await view.getByLabel('Scale block-0').selectOption('4');assert.equal(await view.locator('[data-block-id="block-0"] [role="img"]').getAttribute('style'),'width: 400%;');
 await f.page.locator('.requirement-select').first().dblclick();await f.page.getByLabel('Source block-0').fill('flowchart TD\n ???');await f.button('Preview').click();await f.page.locator('.requirement-editor').getByText(/Block block-0: Unsupported/).waitFor();await f.page.locator('.requirement-editor figure svg').nth(4).waitFor();assert.equal(await f.page.locator('.requirement-editor figure svg').count(),5);await f.save();assert.match(f.doc().proposals[0].requirements[0].diagrams[0].source,/\?\?\?/);
}));
test('HTML/SVG and diagram attacks cannot execute or fetch; safe output and exact source survive',async()=>fixture(async f=>{
 const attack='<h2>Safe heading</h2><script>window.richAttack=1</script><img src="https://rich-attack.example/a" onerror="window.richAttack=2"><iframe src="https://rich-attack.example/frame"></iframe><style>body{display:none}</style><a href="javascript:window.richAttack=3">Unsafe link</a><p onclick="window.richAttack=4" style="position:fixed;inset:0">Visible paragraph</p>';
 await f.write('proposal_requirement',{id:f.destination,requirement:{...f.doc().requirements[0],body_format:'html',description:attack,diagrams:[{id:'unsafe',language:'dot',source:'digraph {a[image="https://rich-attack.example/a"]}',title:'Unsafe diagram',alt:'Original source retained',position:0}]}});await f.reflected();await f.page.locator('.requirement-select').first().click();const view=f.page.locator('.inspector');await view.getByRole('heading',{name:'Safe heading'}).waitFor();await view.getByText(/Preview removed unsafe/).waitFor();await view.getByText(/Block unsafe: Unsupported/).waitFor();assert.equal(await view.locator('.semantic-body script,.semantic-body iframe,.semantic-body img,.semantic-body style,.semantic-body [onclick],.semantic-body [style],.semantic-body a[href]').count(),0);assert.equal(await f.page.evaluate(()=>window.richAttack),undefined);assert.ok(!f.requests.some(url=>url.includes('rich-attack.example')));assert.equal(f.doc().proposals[0].requirements[0].description,attack);
}));
test('ten-source Information controls, metrics, source/reverse navigation, filters and compact keyboard editing',async()=>fixture(async f=>{
 const {page,button}=f;await button('New requirement').click();await page.getByLabel('Item kind',{exact:true}).selectOption('information');await page.getByLabel('Title',{exact:true}).fill('Ten-source explanation');await page.getByLabel('Description',{exact:true}).fill('An explanatory narrative with ten source requirements.');await button('Insert diagram').click();const id=(await page.locator('.diagram-editor legend').first().textContent()).split(' · ')[1];await page.getByLabel('Title '+id,{exact:true}).fill('Ten-source overview');await page.getByLabel('Alternative '+id,{exact:true}).fill('Start and finish summarize all ten requirements.');
 for(let i=1;i<=10;i++){await page.getByLabel('Add source',{exact:true}).selectOption('RB-'+String(i).padStart(3,'0'));await button('Add summarized requirement').click();}await button('Add diagram source mapping').click();await page.getByLabel('Mapped part 1').fill('Start');await page.getByLabel('Mapped sources 1').selectOption(Array.from({length:10},(_,i)=>'RB-'+String(i+1).padStart(3,'0')));await f.save();assert.equal(f.doc().proposals[0].requirements.length,11);assert.equal(f.doc().proposals[0].requirements[10].summarizes.length,10);
 const view=page.locator('.inspector');assert.equal(await view.locator('.source-links li').count(),10);assert.match(await page.locator('.project-summary').textContent(),/10.*1 information/);assert.match(await page.locator('.project-summary').textContent(),/100%/);
 for(let i=1;i<=10;i++){const rid='RB-'+String(i).padStart(3,'0');await view.locator('.source-links li').getByRole('button',{name:new RegExp('^'+rid+' ·')}).click();await view.getByRole('heading',{name:'Source '+(i-1),exact:true}).waitFor();await view.getByRole('button',{name:'RB-011 · Ten-source explanation · Information',exact:true}).click();await view.getByRole('heading',{name:'Ten-source explanation',exact:true}).waitFor();}assert.equal(await page.getByLabel('Working requirements',{exact:true}).inputValue(),f.destination);
 await page.getByLabel('Filter by kind').selectOption('information');assert.equal(await page.locator('.requirement-row').count(),1);await page.getByLabel('Filter by kind').selectOption('requirement');assert.equal(await page.locator('.requirement-row').count(),10);await page.getByLabel('Filter by kind').selectOption('all');
 await page.setViewportSize({width:390,height:844});await page.locator('.mobile-edit').click();await button('Preview').click();await page.locator('.requirement-editor figure svg').waitFor();await page.screenshot({path:'outputs/bl009-compact.png',fullPage:false});await button('Source').click();await page.getByLabel('Description',{exact:true}).focus();await page.keyboard.press('End');await page.keyboard.type(' Keyboard change.');assert.match(await page.getByLabel('Description',{exact:true}).inputValue(),/Keyboard change/);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
}));
test('unavailable renderer preserves fallback without blocking editing',async()=>fixture(async f=>{
 await f.write('proposal_requirement',{id:f.destination,requirement:{...f.doc().requirements[0],diagrams:[{id:'offline',language:'mermaid',source:'flowchart LR\n A-->B',title:'Fallback title',alt:'Fallback alternative',position:0}]}});await f.reflected();await f.page.locator('.requirement-select').first().click();await f.page.locator('.inspector').getByText(/Diagram renderer unavailable/).waitFor();await f.page.locator('.requirement-select').first().dblclick();assert.equal(await f.page.getByLabel('Source offline').inputValue(),'flowchart LR\n A-->B');
},()=>{window.Worker=class{constructor(){throw Error('Unavailable fixture');}};}));
test('worker timeouts and stale asynchronous results preserve latest input and terminate work',async()=>fixture(async f=>{
 await f.write('proposal_requirement',{id:f.destination,requirement:{...f.doc().requirements[0],diagrams:[{id:'slow',language:'mermaid',source:'flowchart LR\n A-->B',title:'Slow title',alt:'Slow alternative',position:0}]}});await f.reflected();await f.page.locator('.requirement-select').first().dblclick();await f.button('Preview').click();await f.page.locator('.requirement-editor').getByText(/Rendering exceeded 2500 ms/).waitFor();assert.equal(await f.page.getByLabel('Source slow').inputValue(),'flowchart LR\n A-->B');await f.page.getByLabel('Source slow').fill('flowchart LR\n New-->Latest');await f.page.locator('.requirement-editor figure svg text').getByText('Latest result',{exact:true}).waitFor();await new Promise(r=>setTimeout(r,350));assert.equal(await f.page.locator('.requirement-editor figure svg').textContent(),'Latest result');assert.ok(await f.page.evaluate(()=>window.terminatedWorkers>0));
},()=>{window.terminatedWorkers=0;window.Worker=class{postMessage(block){if(block.source.includes('New'))setTimeout(()=>this.onmessage?.({data:{svg:'<svg xmlns="http://www.w3.org/2000/svg"><text>Latest result</text></svg>'}}),20);else setTimeout(()=>this.onmessage?.({data:{svg:'<svg xmlns="http://www.w3.org/2000/svg"><text>Old result</text></svg>'}}),2800);}terminate(){window.terminatedWorkers++;}};}));
test('proposal rendered review, human Apply and frozen snapshot source navigation retain context',async()=>fixture(async f=>{
 const {page,button}=f;
 await f.write('proposal_requirement',{id:f.destination,requirement:{section:f.doc().sections[0].id,title:'Snapshot explanation',kind:'information',description:'## Frozen explanation\n\nOriginal body 😀\n',body_format:'markdown',criteria:[],summarizes:f.doc().requirements.map(r=>({requirement_id:r.id})),diagrams:[{id:'review-flow',language:'mermaid',source:'flowchart LR\n A[Source]-->B[Summary]',title:'Reviewed diagram',alt:'The source leads to the summary.',position:0}],diagram_mappings:[{block_id:'review-flow',part:'A',requirement_ids:['RB-001']}]}});await f.reflected();await page.getByRole('tab',{name:/Changes/}).click();await page.locator('.diff-card .rich-content').getByRole('heading',{name:'Frozen explanation'}).waitFor();await page.locator('.diff-card figure svg').waitFor();
 await page.locator('.diff-card .source-links li').first().getByRole('button').click();const reader=page.locator('.snapshot-reader');await reader.getByText('Complete proposed context',{exact:false}).waitFor();await reader.getByRole('button',{name:'RB-011 · Snapshot explanation · Information'}).click();await reader.getByRole('heading',{name:'Snapshot explanation'}).waitFor();await page.keyboard.press('Escape');
 await button('Submit for review').click();await button('Apply 1 change').waitFor();await button('Apply 1 change').click();await button('Apply and snapshot').click();await f.read();await page.locator('.proposal-inclusion').getByRole('button',{name:/BL-002/}).click();await reader.getByRole('heading',{name:/Rich-content draft/}).waitFor();await reader.getByRole('heading',{name:'Frozen explanation'}).waitFor();assert.equal(await reader.locator('.source-links li').count(),10);
 for(let i=1;i<=10;i++){await reader.locator('.source-links li').getByRole('button',{name:new RegExp('^RB-'+String(i).padStart(3,'0')+' ·')}).click();assert.equal(await page.evaluate(()=>document.activeElement.id),'snapshot-item-RB-'+String(i).padStart(3,'0'));await reader.locator('#snapshot-item-RB-'+String(i).padStart(3,'0')).getByRole('button',{name:'RB-011 · Snapshot explanation · Information'}).click();assert.equal(await page.evaluate(()=>document.activeElement.id),'snapshot-item-RB-011');}
 await page.screenshot({path:'outputs/bl009-snapshot.png',fullPage:false});assert.equal((await f.read()).requirements[10].status,'Draft');
}));
test('generated SVG is allowlisted before display and cache reuse',async()=>fixture(async f=>{
 const d={id:'sanitized-svg',language:'mermaid',source:'flowchart LR\n Safe-->Output',title:'Safe SVG',alt:'Safe output remains visible',position:0};await f.write('proposal_requirement',{id:f.destination,requirement:{...f.doc().requirements[0],diagrams:[d]}});await f.reflected();await f.page.locator('.requirement-select').first().click();let svg=f.page.locator('.inspector figure svg');await svg.getByText('Safe output',{exact:true}).waitFor();assert.equal(await svg.locator('script,image,foreignObject,a,[onload],[onclick],[style]').count(),0);assert.equal(await f.page.evaluate(()=>window.svgAttack),undefined);assert.ok(!f.requests.some(url=>url.includes('svg-attack.example')));await f.page.locator('.requirement-select').nth(1).click();await f.page.locator('.requirement-select').first().click();await svg.getByText('Safe output',{exact:true}).waitFor();assert.equal(await svg.locator('script,image,foreignObject,a,[onload],[onclick],[style]').count(),0);
},()=>{window.Worker=class{postMessage(){setTimeout(()=>this.onmessage?.({data:{svg:'<svg xmlns="http://www.w3.org/2000/svg" onload="window.svgAttack=1"><script>window.svgAttack=2</script><image href="https://svg-attack.example/a"/><foreignObject><iframe src="https://svg-attack.example/frame"></iframe></foreignObject><a href="javascript:window.svgAttack=3"><text>Link</text></a><text x="10" y="30" onclick="window.svgAttack=4" style="position:fixed">Safe output</text></svg>'}}),10);}terminate(){}};}));
