import test from 'node:test';
import assert from 'node:assert/strict';
const origin=process.env.WONDERWORKS_TEST_URL??'http://127.0.0.1:5173';
if(!['localhost','127.0.0.1'].includes(new URL(origin).hostname))throw Error('Use loopback QA storage.');
async function rest(body,status=200){const r=await fetch(origin+'/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();assert.equal(r.status,status,JSON.stringify(d));return d;}
const cookie=(await fetch(origin+'/signin-with-chatgpt?return_to=/',{redirect:'manual'})).headers.get('set-cookie').split(';')[0];
async function call(name,args,error){const r=await fetch(origin+'/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream','MCP-Protocol-Version':'2025-11-25',Cookie:cookie},body:JSON.stringify({jsonrpc:'2.0',id:crypto.randomUUID(),method:'tools/call',params:{name,arguments:args}})});const body=await r.json();if(error){assert.equal(body.result?.structuredContent?.error?.code,error,JSON.stringify(body));return body.result.structuredContent.error;}assert.ok(body.result&&!body.result.isError,JSON.stringify(body));return body.result.structuredContent;}
const fields=r=>{const {id,revision,...v}=r;return v;};
for(const language of ['mermaid','dot'])test('independent browser-closed MCP ten-source '+language+' summary round-trip, review, frozen context and complete pagination',async t=>{
 let doc=await rest({action:'project',name:'BL009 '+language+' API '+Date.now(),prefix:'RC'});
 const read=async()=>doc=await(await fetch(origin+'/api/workspace?project='+doc.id)).json();
 const write=async(action,data={},status=200)=>{const result=await rest({project:doc.id,version:doc.version,action,...data},status);if(status===200)doc=result;return result;};
 const args=extra=>({project_id:doc.id,expected_workspace_version:doc.version,idempotency_key:crypto.randomUUID(),...extra});
 await write('section',{section:{title:'Rich specification',description:'Independent MCP fixture'}});
 const req=(i,extra={})=>({section:doc.sections[0].id,title:'Source '+i,description:['  plain <literal> &amp; 😀\n\n\t','## Markdown 😀\n\n**strong** and `code`\n\n```js\nconst x = `value`;\n```\n','<h2>HTML &amp; 😀</h2>\n<p> Body </p>\n'][i%3],body_format:['plain_text','markdown','html'][i%3],criteria:['The measured outcome is observed.'],priority:'High',status:'Approved',...extra});
 const created=await call('create_proposal',args({title:'Ten-source '+language+' summary'}));await read();const proposal_id=created.proposal_id;
 const source=language==='mermaid'?'flowchart LR\n'+Array.from({length:10},(_,i)=>` N${i}[Source ${i}]`).join('\n')+'\n N0 --> N9':'digraph G {\n subgraph cluster_sources {label="Sources";\n'+Array.from({length:10},(_,i)=>` N${i}[label="Source ${i}"];`).join('\n')+'\n } N0 -> N9[label="summarizes"];\n}';
 const summary={section:doc.sections[0].id,title:'Ten-source explanation',kind:'information',body_format:'markdown',description:'## Explanatory overview 😀\n\n  Original spacing.\n\n',diagrams:[{id:'overview',language,source,title:'Ten-source diagram',alt:'Ten requirements are summarized; the first leads to the last.',position:0}],summarizes:Array.from({length:10},(_,i)=>({requirement_id:'$source'+i})),diagram_mappings:Array.from({length:10},(_,i)=>({block_id:'overview',part:'N'+i,requirement_ids:['$source'+i]}))};
 const operations=[{op:'add',client_ref:'summary',requirement:summary},...Array.from({length:10},(_,i)=>({op:'add',client_ref:'source'+i,requirement:req(i)}))];
 const stagedArgs=args({proposal_id,operations});const staged=await call('stage_proposal_changes',stagedArgs);await read();assert.equal(doc.requirements.length,0);assert.deepEqual(await call('stage_proposal_changes',stagedArgs),staged);
 let p=(await call('get_proposal',{project_id:doc.id,proposal_id})).proposal;assert.equal(p.requirements.length,11);assert.equal(p.requirements[0].diagrams[0].source,source);assert.equal(p.requirements[0].criteria.length,0);assert.equal(p.requirements[0].summarizes.length,10);assert.ok(p.requirements[0].summarizes.every(s=>s.reviewed_revision===1));assert.ok(p.changes[0].fields.includes('diagrams'));
 await t.test('validation and stale requests roll back the complete batch including allocated IDs',async()=>{
  const before=structuredClone(doc);for(const operation of [{op:'delete',requirement_id:staged.client_refs.source0},{op:'edit',requirement_id:staged.client_refs.summary,requirement:{...summary,summarizes:[{requirement_id:'RC-999'}],diagram_mappings:[]}},{op:'edit',requirement_id:staged.client_refs.summary,requirement:{...summary,summarizes:[{requirement_id:staged.client_refs.source0},{requirement_id:staged.client_refs.source0}],diagram_mappings:[]}},{op:'edit',requirement_id:staged.client_refs.source0,requirement:req(0,{links:[staged.client_refs.summary]})}])await call('stage_proposal_changes',args({proposal_id,operations:[{op:'add',client_ref:'notReserved',requirement:req(99)},operation]}),'VALIDATION_ERROR');
  await call('stage_proposal_changes',{...args({proposal_id,operations:[{op:'add',client_ref:'stale',requirement:req(99)}]}),expected_workspace_version:doc.version-1},'CONFLICT');assert.deepEqual(await read(),before);
 });
 await call('submit_proposal',args({proposal_id}));await read();await write('proposal_review',{id:proposal_id,review:{decision:'apply',note:'Executed fixture review; no implementation claim.'}});const snapshot=structuredClone(doc.baselines[0]);
 await t.test('complete pagination, kind/status/search and exact snapshots include both kinds',async()=>{
  let cursor,all=[];do{const page=await call('list_requirements',{project_id:doc.id,limit:3,...(cursor?{cursor}:{})});all.push(...page.items);cursor=page.next_cursor;}while(cursor);assert.equal(all.length,11);assert.equal((await call('list_requirements',{project_id:doc.id,kind:'information'})).items.length,1);assert.equal((await call('list_requirements',{project_id:doc.id,status:'Approved'})).items.length,10);assert.equal((await call('list_requirements',{project_id:doc.id,query:'Ten-source diagram'})).items.length,1);
  assert.deepEqual((await call('get_snapshot',{project_id:doc.id,baseline_id:snapshot.id})).snapshot,snapshot);for(let i=0;i<10;i++)assert.equal(doc.requirements[i+1].description,req(i).description);assert.equal(doc.requirements[0].description,summary.description);
  await call('record_evidence',args({evidence:{baseline:snapshot.id,artifactUrl:'https://example.com/qa',summary:'Information is not a verification target.',checks:[{id:staged.client_refs.summary,title:'Forbidden',passed:true,detail:''}]}}),'VALIDATION_ERROR');
 });
 await t.test('source revisions become stale without rewriting summaries; explicit review and rich history preserve old snapshots',async()=>{
  const oldSummary=structuredClone(doc.requirements[0]);await write('proposal',{proposal:{title:'Change one source'}});let id=doc.proposals[0].id;await call('stage_proposal_changes',args({proposal_id:id,operations:[{op:'edit',requirement_id:staged.client_refs.source0,requirement:{...fields(doc.requirements[1]),title:'Changed source zero'}}]}));await read();await call('submit_proposal',args({proposal_id:id}));await read();await write('proposal_review',{id,review:{decision:'apply'}});assert.deepEqual(doc.requirements[0],oldSummary);
  await write('proposal',{proposal:{title:'Review source changes'}});id=doc.proposals[0].id;const edited={...fields(doc.requirements[0]),summarizes:doc.requirements[0].summarizes.map(s=>({...s,reviewed_revision:doc.requirements.find(r=>r.id===s.requirement_id).revision}))};await call('stage_proposal_changes',args({proposal_id:id,operations:[{op:'edit',requirement_id:staged.client_refs.summary,requirement:edited}]}));await read();await call('submit_proposal',args({proposal_id:id}));await read();await write('proposal_review',{id,review:{decision:'apply'}});assert.equal(doc.requirements[0].summarizes[0].reviewed_revision,2);assert.deepEqual((await call('get_snapshot',{project_id:doc.id,baseline_id:snapshot.id})).snapshot,snapshot);
  const history=await call('get_requirement_history',{project_id:doc.id,requirement_id:staged.client_refs.summary});assert.ok(history.items.some(e=>e.fields.includes('summarizes')));assert.equal(history.items[0].after.diagrams[0].source,source);
 });
 await t.test('legacy omissions preserve fields; unchanged imports preserve exact content; malformed diagram can save but cannot submit',async()=>{
  await write('proposal',{proposal:{title:'Legacy edit rich item'}});const id=doc.proposals[0].id;const legacy={...fields(doc.requirements[0]),title:'Legacy client title'};for(const field of ['kind','body_format','diagrams','summarizes','diagram_mappings'])delete legacy[field];await call('stage_proposal_changes',args({proposal_id:id,operations:[{op:'edit',requirement_id:staged.client_refs.summary,requirement:legacy}]}));await read();assert.deepEqual(doc.proposals[0].requirements[0].diagrams,doc.requirements[0].diagrams);const frozen=JSON.stringify(doc.baselines);await write('import',{workspace:structuredClone(doc)});assert.equal(JSON.stringify(doc.baselines),frozen);
  const bad={...fields(doc.proposals[0].requirements[0]),diagrams:[{...summary.diagrams[0],source:language==='dot'?'digraph { nope -> }':'flowchart TD\n ???'}]};await call('stage_proposal_changes',args({proposal_id:id,operations:[{op:'edit',requirement_id:staged.client_refs.summary,requirement:bad}]}));await read();const before=structuredClone(doc);const error=await call('submit_proposal',args({proposal_id:id}),'VALIDATION_ERROR');assert.match(error.message,/RC-001, block overview/);assert.deepEqual(await read(),before);
 });
 await t.test('50,000 Unicode code points survive HTTP staging and one extra is rejected without a save',async()=>{
  const id=doc.proposals[0].id,body='😀'.repeat(50000);await call('stage_proposal_changes',args({proposal_id:id,operations:[{op:'edit',requirement_id:staged.client_refs.source0,requirement:req(0,{description:body})}]}));await read();assert.equal(doc.proposals[0].requirements[1].description,body);const before=structuredClone(doc);const error=await call('stage_proposal_changes',args({proposal_id:id,operations:[{op:'edit',requirement_id:staged.client_refs.source0,requirement:req(0,{description:body+'界'})}]}),'VALIDATION_ERROR');assert.ok(JSON.stringify(error).includes('50000'));assert.deepEqual(await read(),before);
 });
 console.log('BL009_'+language.toUpperCase()+'_API_PROJECT='+doc.id);
});
