'use client';

import {useState} from 'react';
import {GitBranch,GitPullRequest,Plus,Pencil,ExternalLink,Layers,Download,Check,Trash2,RotateCcw,ArrowLeft} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogAction,AlertDialogCancel,AlertDialogFooter} from '@/components/ui/alert-dialog';
import type {Workspace,Requirement,Repository,ChangeProposal,Baseline,Section} from '@/lib/types';
import {requirementChanges,requirementFields,isStale,proposalConflicts,setVersion} from '@/lib/workflow';

type Props={doc:Workspace;mutate:(action:string,data?:Record<string,unknown>)=>Promise<Workspace>;busy:boolean};
const formatDate=(value:string)=>new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
const message=(error:unknown)=>error instanceof Error?error.message:'Unable to save changes';
function SelectField({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){
  return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;
}
function exportJson(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),500);}

export function RepositoryPanel({doc,mutate,busy}:Props){
  const [editing,setEditing]=useState<Partial<Repository>|null>(null),[error,setError]=useState('');
  async function save(event:React.FormEvent){event.preventDefault();try{await mutate('repository',{repository:editing});setEditing(null);}catch(e){setError(message(e));}}
  return <div className="workflow-panel">
    <div className="view-heading"><div><h2>Project repositories</h2><p>Connect this specification to the code that implements it.</p></div><button className="primary" onClick={()=>{setError('');setEditing({name:'',url:'',branch:''});}}><Plus size={16}/>Link repository</button></div>
    <div className="repository-list">{(doc.repositories??[]).map(repo=><article className="repository-card" key={repo.id}><div className="workflow-icon"><GitBranch size={24}/></div><div className="repository-info"><h3><a href={repo.url} target="_blank" rel="noreferrer">{repo.name}<ExternalLink size={15}/></a></h3><p>{repo.url}</p><span className="workflow-meta">{repo.branch?`Branch: ${repo.branch}`:'No branch specified'}</span></div><button className="ghost" aria-label={'Edit repository '+repo.name} onClick={()=>{setError('');setEditing(repo);}}><Pencil size={15}/>Edit</button></article>)}</div>
    {!doc.repositories?.length&&<div className="empty-state"><GitBranch size={32}/><h2>No repository linked</h2><p>Add a repository URL and, optionally, the branch used by this project. Repository links are included in new snapshots.</p></div>}
    <p className="workflow-footnote">Links record where the implementation lives. Linking a repository does not grant access to its code or synchronize commits.</p>
    <Dialog open={!!editing} onOpenChange={open=>{if(!open)setEditing(null);}}><DialogContent><DialogTitle>{editing?.id?'Edit repository link':'Link repository'}</DialogTitle><DialogDescription>Use the repository’s web URL. Branch is optional.</DialogDescription><form className="editor-form" onSubmit={save}>
      <label>Name<input required minLength={2} maxLength={80} value={editing?.name??''} onChange={e=>setEditing({...editing,name:e.target.value})} placeholder="Wonderworks application"/></label>
      <label>Repository URL<input required type="url" maxLength={500} value={editing?.url??''} onChange={e=>setEditing({...editing,url:e.target.value})} placeholder="https://github.com/organization/repository"/></label>
      <label>Branch (optional)<input maxLength={120} value={editing?.branch??''} onChange={e=>setEditing({...editing,branch:e.target.value})} placeholder="main"/></label>
      {error&&<p role="alert" className="error-box">{error}</p>}<div className="editor-actions">{editing?.id&&<button type="button" className="delete-button" disabled={busy} onClick={async()=>{try{await mutate('repository_remove',{id:editing.id});setEditing(null);}catch(e){setError(message(e));}}}>Unlink</button>}<button className="ghost" type="button" onClick={()=>setEditing(null)}>Cancel</button><button className="primary" disabled={busy}>Save link</button></div>
    </form></DialogContent></Dialog>
  </div>;
}

const labels:Record<string,string>={section:'Section',title:'Title',description:'Description',criteria:'Acceptance criteria',priority:'Priority',status:'Status',parameters:'Parameters',links:'Dependencies'};
function FieldValue({field,requirement,sections}:{field:typeof requirementFields[number];requirement?:Requirement;sections:Section[]}){
  if(!requirement)return <span className="diff-empty">Not present</span>;
  const value=requirement[field];
  if(field==='section')return <>{sections.find(s=>s.id===value)?.title??String(value)}</>;
  if(Array.isArray(value))return value.length?<ul>{value.map((item,i)=><li key={i}>{item}</li>)}</ul>:<span className="diff-empty">None</span>;
  if(typeof value==='object')return Object.keys(value).length?<pre>{JSON.stringify(value,null,2)}</pre>:<span className="diff-empty">None</span>;
  return <>{String(value)}</>;
}
function RequirementReadOnly({requirement,sections}:{requirement?:Requirement;sections:Section[]}){
  if(!requirement)return <p className="diff-empty">Requirement removed</p>;
  return <div className="readonly-requirement"><h4>{requirement.title}</h4><p>{requirement.description}</p><div className="workflow-meta">{sections.find(s=>s.id===requirement.section)?.title??requirement.section} · {requirement.priority} · {requirement.status} · r{requirement.revision}</div><ol>{requirement.criteria.map((c,i)=><li key={i}>{c}</li>)}</ol>{Object.keys(requirement.parameters).length>0&&<pre>{JSON.stringify(requirement.parameters,null,2)}</pre>}{requirement.links.length>0&&<p>Depends on {requirement.links.join(', ')}</p>}</div>;
}

export function SnapshotPanel({doc,mutate,busy}:Props){
  const [creating,setCreating]=useState(false),[name,setName]=useState(''),[error,setError]=useState(''),[selected,setSelected]=useState<Baseline|null>(null);
  return <div className="workflow-panel">
    <div className="view-heading"><div><h2>Requirement snapshots</h2><p>Freeze a named copy of the latest requirement set, currently v{setVersion(doc)}.</p></div><button className="primary" onClick={()=>{setName(`Requirement set v${setVersion(doc)}`);setError('');setCreating(true);}}><Plus size={16}/>Create snapshot</button></div>
    {doc.baselines.map((b,i)=><article className="baseline-card" key={b.id}><div className="baseline-icon"><Layers size={25}/></div><div><span className="req-id">{b.id}{b.requirementsVersion?` · SET v${b.requirementsVersion}`:' · LEGACY BASELINE'}{i===0?' · LATEST':''}</span><h3>{b.name}</h3><p>{b.requirements.length} requirements · {b.sections.length} sections · {formatDate(b.date)}</p></div><div className="snapshot-actions"><button className="secondary" onClick={()=>setSelected(b)}>View snapshot</button><button className="ghost" aria-label={'Export snapshot '+b.id} onClick={()=>exportJson(`${doc.name}-${b.id}.json`,b)}><Download size={15}/>Export</button></div></article>)}
    {!doc.baselines.length&&<div className="empty-state"><Layers size={32}/><h2>No snapshots yet</h2><p>Capture a version for implementation or review. Applying a change proposal also creates a snapshot automatically.</p></div>}
    <p className="workflow-footnote">Snapshots preserve requirement revisions, sections, and repository links. Existing baselines remain available for verification.</p>
    <Dialog open={creating} onOpenChange={setCreating}><DialogContent><DialogTitle>Create requirement snapshot</DialogTitle><DialogDescription>Preserve all {doc.requirements.length} requirements in set v{setVersion(doc)}. Future edits leave this snapshot unchanged.</DialogDescription><form className="editor-form" onSubmit={async e=>{e.preventDefault();try{await mutate('baseline',{name});setCreating(false);}catch(e){setError(message(e));}}}><label>Snapshot name<input required minLength={2} maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label>{error&&<p className="error-box" role="alert">{error}</p>}<div className="editor-actions"><button className="ghost" type="button" onClick={()=>setCreating(false)}>Cancel</button><button className="primary" disabled={busy}>Freeze snapshot</button></div></form></DialogContent></Dialog>
    <Sheet open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><SheetContent className="snapshot-reader"><SheetTitle>{selected?.name}</SheetTitle><SheetDescription>{selected?.id} · {selected?.requirementsVersion?`Requirement set v${selected.requirementsVersion}`:'Legacy baseline'} · Read-only snapshot</SheetDescription>{selected&&<><button className="secondary" onClick={()=>exportJson(`${doc.name}-${selected.id}.json`,selected)}><Download size={15}/>Export snapshot</button>{selected.repositories?.map(r=><p className="snapshot-repository" key={r.id}><GitBranch size={16}/><a href={r.url} target="_blank" rel="noreferrer">{r.name}</a>{r.branch&&<span>{r.branch}</span>}</p>)}{selected.sections.map(s=><section key={s.id} className="snapshot-section"><h3>{s.title}</h3><p>{s.description}</p>{selected.requirements.filter(r=>r.section===s.id).map(r=><article className="snapshot-requirement" key={r.id}><span className="req-id">{r.id}</span><RequirementReadOnly requirement={r} sections={selected.sections}/></article>)}</section>)}{!selected.requirements.length&&<p>This snapshot contains an empty requirement set.</p>}</>}</SheetContent></Sheet>
  </div>;
}

function ProposalRequirementEditor({doc,proposal,initial,mutate,busy,onClose}:Props&{proposal:ChangeProposal;initial:Partial<Requirement>;onClose:()=>void}){
  const [draft,setDraft]=useState(initial),[criteria,setCriteria]=useState(initial.criteria?.join('\n')??''),[parameters,setParameters]=useState(JSON.stringify(initial.parameters??{},null,2)),[links,setLinks]=useState(initial.links?.join(', ')??''),[error,setError]=useState('');
  return <Sheet open onOpenChange={open=>{if(!open)onClose();}}><SheetContent className="requirement-editor"><SheetTitle>{draft.id?`Propose edit to ${draft.id}`:'Propose a new requirement'}</SheetTitle><SheetDescription>Save this change to {proposal.id}. The latest requirement set stays unchanged until the proposal is applied.</SheetDescription><form className="editor-form" onSubmit={async e=>{e.preventDefault();try{const values=JSON.parse(parameters);if(!values||Array.isArray(values)||typeof values!=='object')throw Error('Parameters must be a JSON object');await mutate('proposal_requirement',{id:proposal.id,requirement:{...draft,criteria:criteria.split('\n').map(s=>s.trim()).filter(Boolean),parameters:values,links:links.split(',').map(s=>s.trim()).filter(Boolean)}});onClose();}catch(e){setError(message(e));}}}>
    <label>Title<input required minLength={3} maxLength={120} value={draft.title??''} onChange={e=>setDraft({...draft,title:e.target.value})}/></label>
    <label>Section<SelectField label="Proposed requirement section" value={draft.section??''} onChange={section=>setDraft({...draft,section})} options={doc.sections.map(s=>({value:s.id,label:s.title}))}/></label>
    <div className="form-grid"><label>Priority<SelectField label="Proposed priority" value={draft.priority??'High'} onChange={priority=>setDraft({...draft,priority:priority as Requirement['priority']})} options={['Critical','High','Medium'].map(value=>({value,label:value}))}/></label><label>Status<SelectField label="Proposed status" value={draft.status??'Draft'} onChange={status=>setDraft({...draft,status:status as Requirement['status']})} options={['Draft','Approved','Implemented'].map(value=>({value,label:value}))}/></label></div>
    <label>Description<textarea required minLength={10} maxLength={4000} rows={5} value={draft.description??''} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>
    <label>Acceptance criteria<span className="field-hint">One measurable outcome per line</span><textarea required rows={5} value={criteria} onChange={e=>setCriteria(e.target.value)}/></label>
    <label>Dependencies<input value={links} onChange={e=>setLinks(e.target.value)} placeholder={`${doc.prefix}-001, ${doc.prefix}-002`}/><span className="field-hint">Reference requirements retained or added in this proposal.</span></label>
    <details><summary>Specified parameters</summary><textarea aria-label="Proposed requirement parameters JSON" className="code-input" rows={5} value={parameters} onChange={e=>setParameters(e.target.value)}/></details>
    {error&&<p className="error-box" role="alert">{error}</p>}<div className="editor-actions"><button className="ghost" type="button" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>Save to proposal</button></div>
  </form></SheetContent></Sheet>;
}

export function ProposalPanel({doc,mutate,busy}:Props){
  const [selected,setSelected]=useState(''),[creating,setCreating]=useState(false),[details,setDetails]=useState(false),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[error,setError]=useState(''),[stage,setStage]=useState(false),[query,setQuery]=useState(''),[editing,setEditing]=useState<Partial<Requirement>|null>(null),[reviewNote,setReviewNote]=useState(''),[confirmApply,setConfirmApply]=useState(false),[resolutions,setResolutions]=useState<Record<string,'proposed'|'latest'>>({});
  const proposals=doc.proposals??[],p=proposals.find(p=>p.id===selected)??proposals[0];
  const changes=p?requirementChanges(p.baseRequirements,p.requirements):[],stale=p?isStale(doc,p):false,conflicts=p?proposalConflicts(doc,p):[];
  const open=p&&['Draft','Proposed'].includes(p.status),counts={Added:changes.filter(c=>c.kind==='Added').length,Edited:changes.filter(c=>c.kind==='Edited').length,Deleted:changes.filter(c=>c.kind==='Deleted').length};
  async function act(action:string,data:Record<string,unknown>={}){setError('');try{return await mutate(action,{id:p?.id,...data});}catch(e){setError(message(e));return null;}}
  function choose(id:string){setSelected(id);setStage(false);setError('');setReviewNote('');setResolutions({});setQuery('');}
  return <div className="workflow-panel">
    <div className="view-heading"><div><h2>Change proposals</h2><p>Review a batch of changes before it becomes the latest requirement set.</p></div><button className="primary" onClick={()=>{setTitle('');setDescription('');setError('');setCreating(true);}}><Plus size={16}/>New proposal</button></div>
    {!p?<div className="empty-state"><GitPullRequest size={34}/><h2>Start a change proposal</h2><p>Draft additions, edits, and deletions against requirement set v{setVersion(doc)}. Submit the batch for review, then apply it in one step.</p></div>:<div className="proposal-layout">
      <nav className="proposal-list" aria-label="Change proposals">{proposals.map(item=><button key={item.id} className={'proposal-list-item '+(item.id===p.id?'selected':'')} onClick={()=>choose(item.id)}><span className="proposal-list-meta"><span className="req-id">{item.id}</span><span className={'badge '+item.status.toLowerCase()}>{item.status}</span></span><strong>{item.title}</strong><span className="workflow-meta">Based on v{item.baseVersion} · {requirementChanges(item.baseRequirements,item.requirements).length} changes</span></button>)}</nav>
      <div className="proposal-detail">
        <header className="proposal-header"><div className="proposal-list-meta"><span className="req-id">{p.id}</span><span className={'badge '+p.status.toLowerCase()}>{p.status}</span><span className="workflow-meta">{formatDate(p.updatedAt)}</span></div><h3>{p.title}</h3>{p.description&&<p>{p.description}</p>}<div className="proposal-version">Base <strong>v{p.baseVersion}</strong><span>Latest <strong>v{setVersion(doc)}</strong></span>{p.appliedVersion&&<span>Applied as <strong>v{p.appliedVersion}</strong> · {p.appliedSnapshot}</span>}</div></header>
        <div className="change-counts"><span className="added">{counts.Added} added</span><span className="edited">{counts.Edited} edited</span><span className="deleted">{counts.Deleted} deleted</span></div>
        {p.reviewNote&&<div className="review-note"><strong>Review note</strong><p>{p.reviewNote}</p></div>}
        {open&&stale&&<div className="stale-notice"><h4>The latest requirement set has changed</h4><p>Refresh this proposal onto v{setVersion(doc)} before submitting or applying it. Unrelated changes are kept; conflicting requirements need your decision.</p>{conflicts.map(id=><details className="conflict-card" key={id} open><summary>{id} changed in both versions</summary><div className="conflict-columns"><div><h5>Proposed</h5><RequirementReadOnly requirement={p.requirements.find(r=>r.id===id)} sections={p.baseSections}/></div><div><h5>Latest</h5><RequirementReadOnly requirement={doc.requirements.find(r=>r.id===id)} sections={doc.sections}/></div></div><SelectField label={'Resolve conflict '+id} value={resolutions[id]??''} onChange={value=>setResolutions({...resolutions,[id]:value as 'proposed'|'latest'})} options={[{value:'proposed',label:'Keep proposed requirement'},{value:'latest',label:'Use latest requirement'}]}/></details>)}<button className="secondary" disabled={busy||conflicts.some(id=>!resolutions[id])} onClick={async()=>{if(await act('proposal_rebase',{resolutions})){setResolutions({});setStage(false);}}}><RotateCcw size={15}/>Refresh from latest</button></div>}
        {error&&<p className="error-box" role="alert">{error}</p>}
        {p.status==='Draft'&&<div className="proposal-toolbar"><button className={stage?'secondary':'ghost'} onClick={()=>setStage(!stage)}>{stage?<><ArrowLeft size={15}/>Review changes</>:<><Pencil size={15}/>Edit requirement batch</>}</button><button className="ghost" onClick={()=>{setTitle(p.title);setDescription(p.description);setDetails(true);setError('');}}>Edit proposal details</button><button className="primary" disabled={busy||stale||!changes.length} onClick={async()=>{if(await act('proposal_submit'))setStage(false);}}>Submit for review</button></div>}
        {stage&&p.status==='Draft'?<div className="staging-panel"><div className="staging-toolbar"><input aria-label="Find requirements to change" placeholder="Find requirements to change…" value={query} onChange={e=>setQuery(e.target.value)}/><button className="secondary" disabled={!doc.sections.length||busy} onClick={()=>setEditing({section:doc.sections[0]?.id,title:'',description:'',priority:'High',status:'Draft'})}><Plus size={15}/>Add requirement</button></div>{!doc.sections.length&&<p className="workflow-footnote">Create a section in Requirements before adding a requirement.</p>}{p.requirements.filter(r=>!query||`${r.id} ${r.title} ${r.description}`.toLowerCase().includes(query.toLowerCase())).map(r=><div className="staging-row" key={r.id}><div><span className="req-id">{r.id}</span><strong>{r.title}</strong><span className="workflow-meta">{changes.find(c=>c.id===r.id)?.kind??'Unchanged'} · {r.priority} · {r.status}</span></div><button className="ghost" aria-label={'Propose edit '+r.id} onClick={()=>setEditing(r)}><Pencil size={15}/>Edit</button><button className="ghost" disabled={busy} aria-label={'Stage deletion '+r.id} onClick={()=>void act('proposal_delete',{requirementId:r.id})}><Trash2 size={15}/></button></div>)}{changes.filter(c=>c.kind==='Deleted').map(c=><div className="staging-row staged-deletion" key={c.id}><div><span className="req-id">{c.id}</span><strong>{c.before?.title}</strong><span className="workflow-meta">Staged for deletion</span></div><button className="ghost" disabled={busy} onClick={()=>void act('proposal_restore',{requirementId:c.id})}><RotateCcw size={15}/>Restore</button></div>)}</div>:<div className="proposal-diff">{!changes.length&&<div className="empty-state"><GitPullRequest size={28}/><h2>No changes staged</h2><p>Choose Edit requirement batch to add, edit, or remove requirements.</p></div>}{changes.map(change=><article className={'diff-card '+change.kind.toLowerCase()} key={change.id}><header><span className="req-id">{change.id}</span><span className={'change-kind '+change.kind.toLowerCase()}>{change.kind}</span><h4>{change.after?.title??change.before?.title}</h4>{p.status==='Draft'&&<button className="ghost" disabled={busy} aria-label={'Undo change '+change.id} onClick={()=>void act('proposal_restore',{requirementId:change.id})}><RotateCcw size={14}/>Undo</button>}</header><div className="diff-column-labels"><span>Before · v{p.baseVersion}</span><span>Proposed{p.appliedVersion?` · v${p.appliedVersion}`:''}</span></div>{change.fields.map(field=><div className="diff-field" key={field}><h5>{labels[field]}</h5><div className="diff-values"><div className="diff-before"><FieldValue field={field} requirement={change.before} sections={p.baseSections}/></div><div className="diff-after"><FieldValue field={field} requirement={change.after} sections={p.baseSections}/></div></div></div>)}</article>)}</div>}
        {p.status==='Proposed'&&<div className="review-decision"><h4>Review this change set</h4><p>Applying updates the latest requirement set atomically and creates an immutable snapshot.</p><label>Review note (optional)<textarea rows={3} maxLength={3000} value={reviewNote} onChange={e=>setReviewNote(e.target.value)} placeholder="Why this change is ready, or what needs to change"/></label><div className="review-actions"><button className="ghost" disabled={busy} onClick={()=>void act('proposal_review',{review:{decision:'request_changes',note:reviewNote}})}>Request changes</button><button className="ghost reject-action" disabled={busy} onClick={()=>void act('proposal_review',{review:{decision:'reject',note:reviewNote}})}>Reject proposal</button><button className="primary" disabled={busy||stale} onClick={()=>setConfirmApply(true)}><Check size={16}/>Apply {changes.length} {changes.length===1?'change':'changes'}</button></div></div>}
      </div>
    </div>}
    <Dialog open={creating||details} onOpenChange={open=>{if(!open){setCreating(false);setDetails(false);}}}><DialogContent><DialogTitle>{creating?'New change proposal':'Edit proposal details'}</DialogTitle><DialogDescription>{creating?`Start from the latest requirement set, v${setVersion(doc)}. Your proposed changes stay separate until reviewed and applied.`:'Describe the intent and scope of this batch.'}</DialogDescription><form className="editor-form" onSubmit={async e=>{e.preventDefault();setError('');try{const result=await mutate(creating?'proposal':'proposal_update',{id:p?.id,proposal:{title,description}});if(creating){choose(result.proposals![0].id);setStage(true);}setCreating(false);setDetails(false);}catch(e){setError(message(e));}}}><label>Proposal title<input required minLength={3} maxLength={120} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Clarify the review and approval workflow"/></label><label>Reason for this change<textarea rows={4} maxLength={3000} value={description} onChange={e=>setDescription(e.target.value)}/></label>{error&&<p className="error-box" role="alert">{error}</p>}<div className="editor-actions"><button type="button" className="ghost" onClick={()=>{setCreating(false);setDetails(false);}}>Cancel</button><button className="primary" disabled={busy}>{creating?'Create draft':'Save details'}</button></div></form></DialogContent></Dialog>
    {editing&&p&&<ProposalRequirementEditor doc={doc} mutate={mutate} busy={busy} proposal={p} initial={editing} onClose={()=>setEditing(null)}/>}
    <AlertDialog open={confirmApply} onOpenChange={setConfirmApply}><AlertDialogContent><AlertDialogTitle>Apply {p?.id} to the latest requirement set?</AlertDialogTitle><AlertDialogDescription>This applies {counts.Added} additions, {counts.Edited} edits, and {counts.Deleted} deletions together. A snapshot of the resulting version will be saved.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep reviewing</AlertDialogCancel><AlertDialogAction disabled={busy||stale} onClick={()=>void act('proposal_review',{review:{decision:'apply',note:reviewNote}})}>Apply and snapshot</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
