'use client';
import {useRef,useState,useLayoutEffect} from 'react';
import type {Requirement,DiagramBlock} from '@/lib/types';
import {contentSize,codePoints,formatOf,diagramsOf,normative,sourceFreshness} from '@/lib/item-content';
import {RichContent} from './rich-content';
export function RichContentEditor({item,onChange,items}:{item:Partial<Requirement>;onChange:(value:Partial<Requirement>)=>void;items:Requirement[]}){
 const [preview,setPreview]=useState(false),[query,setQuery]=useState(''),[sourceId,setSourceId]=useState('');const source=useRef<HTMLTextAreaElement>(null),selection=useRef([0,0]),restoreFocus=useRef(false);
 useLayoutEffect(()=>{if(!preview&&restoreFocus.current){restoreFocus.current=false;source.current?.focus();source.current?.setSelectionRange(...selection.current as [number,number]);}},[preview]);
 const blocks=item.diagrams??[],summaries=item.summarizes??[],mappings=item.diagram_mappings??[],isInformation=!normative(item);
 function updateBlock(id:string,value:Partial<DiagramBlock>){onChange({...item,diagrams:blocks.map(d=>d.id===id?{...d,...value}:d)});}
 function tab(value:boolean){if(value&&source.current)selection.current=[source.current.selectionStart,source.current.selectionEnd];restoreFocus.current=!value;setPreview(value);}
 const available=items.filter(r=>normative(r)&&r.id!==item.id&&!summaries.some(s=>s.requirement_id===r.id)&&`${r.id} ${r.title}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="rich-editor">
  <label>Body format<select aria-label="Body format" value={formatOf(item)} onChange={e=>{onChange({...item,body_format:e.target.value as Requirement['body_format']});tab(true);}}><option value="plain_text">Plain text</option><option value="markdown">Markdown</option><option value="html">HTML</option></select></label>
  <div className="source-preview-tabs" role="group" aria-label="Body view"><button type="button" aria-pressed={!preview} onClick={()=>tab(false)}>Source</button><button type="button" aria-pressed={preview} onClick={()=>tab(true)}>Preview</button></div>
  <label hidden={preview}>Description<textarea ref={source} aria-label="Description" rows={10} value={item.description??''} onChange={e=>onChange({...item,description:e.target.value})} spellCheck={false}/></label>
  {preview&&<RichContent item={item} showSource={false}/>}
  <p className="field-hint">{contentSize(item).toLocaleString()} / 50,000 Unicode characters across body, diagram source, titles and alternatives. Source whitespace is preserved.</p>
  <details className="diagram-help"><summary>Supported diagram syntax and limits</summary><p>Mermaid core: flowchart TD/TB/BT/LR/RL with labeled nodes, chained arrows, pipe edge labels and one-level subgraphs; sequenceDiagram participants, actors and messages; stateDiagram-v2 states and transitions. Other Mermaid statements are reported as unsupported.</p><p>Graphviz DOT: directed/undirected graphs, labeled nodes and edges, grouped subgraphs, basic shapes and colors. Scripts, callbacks, directives, stylesheets, includes, images and external resources are disabled. Each block allows 12,000 characters, 100 nodes, 200 edges, 12 groups and 2.5 seconds of rendering; source is always retained.</p><p>Explicit blocks work with every format. Position is an offset in body Unicode characters; blocks at the same position keep list order. Markdown also recognizes mermaid, dot and graphviz fences. Add id=your-id after the fence language for a stable mapping ID. Inline fence source is edited only in the body.</p></details>
  <div className="rich-editor-heading"><h4>Diagram blocks</h4><button type="button" className="secondary" onClick={()=>onChange({...item,diagrams:[...blocks,{id:'diagram-'+crypto.randomUUID().slice(0,8),language:'mermaid',source:'flowchart LR\n  A[Start] --> B[Finish]',title:'',alt:'',position:codePoints(item.description??'')}]})}>Insert diagram</button></div>
  {blocks.map((d,i)=><fieldset className="diagram-editor" key={d.id}><legend>Diagram {i+1} · {d.id}</legend><label>Language<select aria-label={'Language '+d.id} value={d.language} onChange={e=>updateBlock(d.id,{language:e.target.value as DiagramBlock['language']})}><option value="mermaid">Mermaid</option><option value="dot">Graphviz DOT</option></select></label><label>Diagram title<input aria-label={'Title '+d.id} value={d.title} onChange={e=>updateBlock(d.id,{title:e.target.value})}/></label><label>Text alternative<textarea aria-label={'Alternative '+d.id} rows={2} value={d.alt} onChange={e=>updateBlock(d.id,{alt:e.target.value})}/></label><label>Diagram source<textarea aria-label={'Source '+d.id} rows={6} spellCheck={false} value={d.source} onChange={e=>updateBlock(d.id,{source:e.target.value})}/></label><label>Position in body<input aria-label={'Position '+d.id} type="number" min={0} max={codePoints(item.description??'')} value={d.position} onChange={e=>updateBlock(d.id,{position:Number(e.target.value)})}/></label><button type="button" className="ghost" onClick={()=>onChange({...item,diagrams:blocks.filter(b=>b.id!==d.id),diagram_mappings:mappings.filter(m=>m.block_id!==d.id)})}>Remove diagram {i+1}</button></fieldset>)}
  {isInformation&&<><h4>Sources · summarized requirements</h4><label>Find source by ID or title<input aria-label="Find source" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Add source<select aria-label="Add source" value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">Choose a requirement</option>{available.map(r=><option key={r.id} value={r.id}>{r.id} · {r.title} · r{r.revision}</option>)}</select></label><button type="button" className="secondary" disabled={!available.some(r=>r.id===sourceId)} onClick={()=>{const r=available.find(r=>r.id===sourceId)!;onChange({...item,summarizes:[...summaries,{requirement_id:r.id,reviewed_revision:r.revision}]});setSourceId('');}}>Add summarized requirement</button>
  {summaries.map(s=>{const r=items.find(r=>r.id===s.requirement_id);return <div className="source-editor" key={s.requirement_id}><strong>{s.requirement_id} · {r?.title??'Unavailable'} · r{r?.revision??'?'}</strong><p>{sourceFreshness(s,items)} · Reviewed r{s.reviewed_revision??'Unknown'}</p><details><summary>Inspect current source</summary>{r&&<RichContent item={r}/>}</details><button type="button" className="ghost" disabled={!r} onClick={()=>onChange({...item,summarizes:summaries.map(v=>v.requirement_id===s.requirement_id?{...v,reviewed_revision:r!.revision}:v)})}>Mark {s.requirement_id} reviewed</button><button type="button" className="ghost" onClick={()=>onChange({...item,summarizes:summaries.filter(v=>v!==s),diagram_mappings:mappings.map(m=>({...m,requirement_ids:m.requirement_ids.filter(id=>id!==s.requirement_id)})).filter(m=>m.requirement_ids.length)})}>Remove source {s.requirement_id} and its mappings</button></div>;})}
  <p className="field-hint">Markers change only when you add a source or explicitly mark it reviewed. Final staged source revisions are checked on submission. Freshness does not verify the summary.</p>
  <h4>Diagram source mappings</h4>{mappings.map((m,i)=><fieldset className="diagram-editor" key={i}><legend>Mapping {i+1}</legend><label>Diagram<select aria-label={'Mapping block '+(i+1)} value={m.block_id} onChange={e=>onChange({...item,diagram_mappings:mappings.map((v,n)=>n===i?{...v,block_id:e.target.value}:v)})}>{diagramsOf(item).map(d=><option key={d.id} value={d.id}>{d.id} · {d.title}</option>)}</select></label><label>Node or labeled part<input aria-label={'Mapped part '+(i+1)} required value={m.part} onChange={e=>onChange({...item,diagram_mappings:mappings.map((v,n)=>n===i?{...v,part:e.target.value}:v)})}/></label><label>Source requirements<select multiple aria-label={'Mapped sources '+(i+1)} value={m.requirement_ids} onChange={e=>onChange({...item,diagram_mappings:mappings.map((v,n)=>n===i?{...v,requirement_ids:Array.from(e.target.selectedOptions).map(o=>o.value)}:v)})}>{summaries.map(s=><option key={s.requirement_id} value={s.requirement_id}>{s.requirement_id}</option>)}</select></label><button type="button" className="ghost" onClick={()=>onChange({...item,diagram_mappings:mappings.filter((_,n)=>n!==i)})}>Remove mapping {i+1}</button></fieldset>)}<button type="button" className="secondary" disabled={!summaries.length||!diagramsOf(item).length} onClick={()=>onChange({...item,diagram_mappings:[...mappings,{block_id:diagramsOf(item)[0].id,part:'',requirement_ids:[summaries[0].requirement_id]}]})}>Add diagram source mapping</button></>}
 </section>;
}
