import {z} from 'zod';
import type {Workspace,Requirement} from './types';
export const requirementInput=z.object({id:z.string().regex(/^[A-Z]{2,6}-\d{3,6}$/).optional(),section:z.string().min(1).max(80),title:z.string().trim().min(3).max(120),description:z.string().trim().min(10).max(4000),criteria:z.array(z.string().trim().min(3).max(1500)).min(1).max(20),priority:z.enum(['Critical','High','Medium']),status:z.enum(['Draft','Approved','Implemented']),parameters:z.record(z.union([z.number().finite(),z.string().max(120),z.boolean()])).default({}),links:z.array(z.string().regex(/^[A-Z]{2,6}-\d{3,6}$/)).max(30).default([])});
export function nextId(doc:Workspace){const previous=[...doc.requirements,...doc.baselines.flatMap(b=>b.requirements)].reduce((m,r)=>Math.max(m,Number(r.id.split('-')[1])),0);const n=Math.max(doc.nextSequence??1,previous+1);doc.nextSequence=n+1;return `${doc.prefix}-${String(n).padStart(3,'0')}`;}
export function validateDependencies(doc:Workspace){const visiting=new Set<string>(),done=new Set<string>();const visit=(id:string)=>{if(visiting.has(id))throw new Error('Dependency links cannot form a cycle');if(done.has(id))return;visiting.add(id);for(const link of doc.requirements.find(r=>r.id===id)?.links??[])visit(link);visiting.delete(id);done.add(id);};for(const r of doc.requirements)visit(r.id);}
export function record(doc:Workspace,message:string){doc.history.unshift({id:crypto.randomUUID(),date:new Date().toISOString(),message});doc.history=doc.history.slice(0,500);}
export function upsert(doc:Workspace,input:unknown){const data=requirementInput.parse(input);if(!doc.sections.some(s=>s.id===data.section))throw new Error('Choose an existing section');const existing=doc.requirements.find(r=>r.id===data.id);if(data.id&&!existing)throw new Error('Requirement no longer exists');const id=existing?.id??nextId(doc);for(const link of data.links){if(link===id||!doc.requirements.some(r=>r.id===link))throw new Error('Dependencies must reference other existing requirements');}if(existing&&(['section','title','description','criteria','priority','status','parameters','links'] as const).every(key=>JSON.stringify(existing[key])===JSON.stringify(data[key])))return existing;const requirement:Requirement={...data,id,revision:(existing?.revision??0)+1};if(existing)doc.requirements[doc.requirements.indexOf(existing)]=requirement;else doc.requirements.push(requirement);record(doc,`${id} ${existing?'revised to r'+requirement.revision:'created'} · ${requirement.title}`);return requirement;}
export function exportSpecification(doc:Workspace){return `# ${doc.name} — requirements\n\nAuthoritative game specification. Workspace revision ${doc.version}.\n\n`+doc.sections.map(s=>`## ${s.title}\n\n${s.description}\n\n`+doc.requirements.filter(r=>r.section===s.id).map(r=>`### ${r.id}: ${r.title}\n\nRevision ${r.revision} · ${r.priority} · ${r.status}\n\n${r.description}\n\nAcceptance criteria:\n${r.criteria.map(c=>'- '+c).join('\n')}\n\n${Object.keys(r.parameters).length?'Parameters:\n```json\n'+JSON.stringify(r.parameters,null,2)+'\n```\n':''}${r.links.length?'Dependencies: '+r.links.join(', ')+'\n':''}`).join('\n')).join('\n');}

const snapshotRequirement=requirementInput.extend({id:z.string().regex(/^[A-Z]{2,6}-\d{3,6}$/),revision:z.number().int().positive()});
const sectionSchema=z.object({id:z.string().min(1),title:z.string().min(2).max(70),description:z.string().max(300)});
const baselineSchema=z.object({id:z.string().regex(/^BL-\d+$/),name:z.string().min(2).max(100),date:z.string().datetime(),requirements:z.array(snapshotRequirement).max(1000),sections:z.array(sectionSchema).max(100)});
export const workspaceImport=z.object({id:z.string().min(1),prefix:z.string().regex(/^[A-Z]{2,6}$/),name:z.string().min(2).max(80),version:z.number().int().nonnegative(),nextSequence:z.number().int().positive().optional(),sections:z.array(sectionSchema).max(100),requirements:z.array(snapshotRequirement).max(1000),baselines:z.array(baselineSchema).max(100),evidence:z.array(z.object({id:z.string(),date:z.string().datetime(),baseline:z.string(),artifactUrl:z.string().url().refine(s=>['https:','http:'].includes(new URL(s).protocol)),summary:z.string(),checks:z.array(z.object({id:z.string(),title:z.string(),passed:z.boolean(),detail:z.string()}))})).max(500),history:z.array(z.object({id:z.string(),date:z.string().datetime(),message:z.string()})).max(1000)});
function canonical(value:unknown):string{if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value&&typeof value==='object')return '{'+Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>JSON.stringify(k)+':'+canonical(v)).join(',')+'}';return JSON.stringify(value);}
export function reconcileWorkspace(current:Workspace,input:unknown){const imported=workspaceImport.parse(input);if(imported.id!==current.id||imported.prefix!==current.prefix)throw Error('Import must target the same project');for(const b of current.baselines){const next=imported.baselines.find(n=>n.id===b.id);if(!next||canonical(next)!==canonical(b))throw Error('Import cannot change or remove existing baselines');}for(const r of current.requirements){const next=imported.requirements.find(n=>n.id===r.id);if(!next||next.revision<r.revision||(next.revision===r.revision&&canonical(next)!==canonical(r)))throw Error('Import conflicts with an existing requirement revision');}for(const e of current.evidence){const next=imported.evidence.find(n=>n.id===e.id);if(!next||canonical(next)!==canonical(e))throw Error('Import cannot change existing evidence');}if(new Set(imported.requirements.map(r=>r.id)).size!==imported.requirements.length||new Set(imported.sections.map(s=>s.id)).size!==imported.sections.length||new Set(imported.baselines.map(b=>b.id)).size!==imported.baselines.length)throw Error('Import has duplicate IDs');for(const r of imported.requirements){if(!imported.sections.some(s=>s.id===r.section)||r.links.some(id=>!imported.requirements.some(n=>n.id===id)))throw Error('Import has missing sections or dependencies');}validateDependencies(imported);Object.assign(current,imported,{version:current.version});record(current,'Requirements and immutable baselines synchronized from an exported workspace');}
